package com.brightnest.app.ui

data class Story(
    val id: String,
    val emoji: String,
    val titleEn: String,
    val titleUr: String,
    val titleAr: String = "",
    val titleHi: String = "",
    val taglineEn: String,
    val taglineUr: String,
    val taglineAr: String = "",
    val taglineHi: String = "",
    val lessonEn: String,
    val lessonUr: String,
    val lessonAr: String = "",
    val lessonHi: String = "",
    val contentEn: String,
    val contentUr: String,
    val contentAr: String = "",
    val contentHi: String = ""
) {
    fun getLocalizedTitle(langCode: String): String {
        return when (langCode.lowercase()) {
            "ur" -> titleUr.ifEmpty { titleEn }
            "ar" -> titleAr.ifEmpty { titleUr.ifEmpty { titleEn } }
            "hi" -> titleHi.ifEmpty { titleEn }
            else -> titleEn
        }
    }

    fun getLocalizedTagline(langCode: String): String {
        return when (langCode.lowercase()) {
            "ur" -> taglineUr.ifEmpty { taglineEn }
            "ar" -> taglineAr.ifEmpty { taglineUr.ifEmpty { taglineEn } }
            "hi" -> taglineHi.ifEmpty { taglineEn }
            else -> taglineEn
        }
    }

    fun getLocalizedLesson(langCode: String): String {
        return when (langCode.lowercase()) {
            "ur" -> lessonUr.ifEmpty { lessonEn }
            "ar" -> lessonAr.ifEmpty { lessonUr.ifEmpty { lessonEn } }
            "hi" -> lessonHi.ifEmpty { lessonEn }
            else -> lessonEn
        }
    }

    fun getLocalizedContent(langCode: String): String {
        return when (langCode.lowercase()) {
            "ur" -> contentUr.ifEmpty { contentEn }
            "ar" -> contentAr.ifEmpty { contentUr.ifEmpty { contentEn } }
            "hi" -> contentHi.ifEmpty { contentEn }
            else -> contentEn
        }
    }
}

object StoriesData {
    val stories: List<Story> = listOf(
        Story(
            id = "adam",
            emoji = "👤",
            titleEn = "Prophet Adam",
            titleUr = "حضرت آدم علیہ السلام",
            titleAr = "نبي الله آدم عليه السلام",
            titleHi = "पैगंबर आदम (अलैहिस्सलाम)",
            taglineEn = "The First Human",
            taglineUr = "پہلے انسان",
            taglineAr = "أول البشر",
            taglineHi = "पहले इंसान",
            lessonEn = "We all make mistakes — what matters is sincere repentance.",
            lessonUr = "ہم سب سے غلطیاں ہوتی ہیں — اصل بات سچی توبہ ہے۔",
            lessonAr = "كلنا نخطئ — ولكن الأهم هو التوبة الصادقة والرجوع إلى الله.",
            lessonHi = "हम सभी से गलतियाँ होती हैं — सबसे ज़रूरी है सच्ची तौबा करना।",
            contentEn = "Allah created Adam (peace be upon him) from clay and breathed life into him. He was the first human and the first prophet. Allah taught Adam the names of every thing, then told the angels to honor him. All the angels bowed in respect except Iblis (Shaytan), who was proud and refused. Because of his arrogance, Iblis was thrown out of Allah's mercy forever.\n\nAdam and his wife Hawwa (Eve) lived in Paradise. They could eat from any tree except one. Shaytan whispered to them again and again until they ate from that forbidden tree. The moment they did, they felt deeply sorry. They cried out, 'Our Lord, we have wronged ourselves. If You do not forgive us and have mercy on us, we will surely be among the losers.'\n\nAllah, the Most Forgiving, accepted their repentance and sent them to earth to live, work, and worship Him. From Adam and Hawwa came all the people of the world. Adam taught his children to pray, to be kind to each other, and to always turn back to Allah whenever they made a mistake — because Allah loves those who turn back to Him.",
            contentUr = "اللہ تعالیٰ نے حضرت آدم علیہ السلام کو مٹی سے بنایا اور ان میں اپنی روح پھونکی۔ آپ پہلے انسان اور پہلے نبی تھے۔ اللہ نے آدم کو ہر چیز کے نام سکھائے، پھر فرشتوں کو حکم دیا کہ ان کو سجدہ کریں۔ سب فرشتوں نے ادب سے سجدہ کیا سوائے ابلیس (شیطان) کے، جس نے تکبر کیا اور انکار کر دیا۔ اپنے تکبر کی وجہ سے ابلیس ہمیشہ کے لیے اللہ کی رحمت سے دور کر دیا گیا۔\n\nحضرت آدم اور ان کی بیوی حواؑ جنت میں رہنے لگے۔ وہ ہر درخت سے کھا سکتے تھے سوائے ایک کے۔ شیطان نے بار بار وسوسے ڈالے یہاں تک کہ انہوں نے اس منع کیے ہوئے درخت سے کھا لیا۔ جیسے ہی انہوں نے ایسا کیا، وہ بہت شرمندہ ہوئے اور پکار اٹھے: 'اے ہمارے رب! ہم نے اپنی جانوں پر ظلم کیا، اگر تو ہمیں معاف نہ کرے گا اور رحم نہ کرے گا تو ہم خسارہ پانے والوں میں ہو جائیں گے۔'\n\nاللہ بہت معاف کرنے والا ہے، اس نے ان کی توبہ قبول فرما لی اور انہیں زمین پر بھیجا تاکہ وہ یہاں رہیں، محنت کریں اور اللہ کی عبادت کریں۔ آدم اور حواؑ ہی سے دنیا کے سب لوگ پیدا ہوئے۔ آدم علیہ السلام نے اپنی اولاد کو نماز پڑھنا، ایک دوسرے سے محبت کرنا اور ہر غلطی پر فوراً اللہ کی طرف لوٹنا سکھایا — کیونکہ اللہ توبہ کرنے والوں سے محبت کرتا ہے۔",
            contentAr = "خلق الله تعالى آدم عليه السلام من طين ونفخ فيه من روحه، فكان أول إنسان وأول نبي على وجه الأرض. علم الله آدم الأسماء كلها ثم أمر الملائكة بالسجود له تكريماً. سجد الملائكة جميعاً بطاعة وإجلال، إلا إبليس (الشيطان) الذي استكبر ورفض السجود، فطُرِد من رحمة الله إلى يوم الدين.\n\nعاش آدم وزوجته حواء في الجنة، وكان يجوز لهما الأكل من كل ثمارها ما عدا شجرة واحدة. ظل الشيطان يوسوس لهما حتى أكلَا من الشجرة المحرمة. وما إن فعلا ذلك حتى شعرا بالندم الشديد ودعوا الله قائلين: 'رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ'.\n\nقبل الله التواب الغفور توبتهما، وأهبطهما إلى الأرض ليعمراها ويعبداه وحده. ومن آدم وحواء جاءت البشرية جمعاء. علم آدم أبناءه الصلاة والرحمة والرجوع إلى الله فور وقوع الخطأ، لأن الله يحب التوابين ويحب المتطهرين.",
            contentHi = "अल्लाह ने हज़रत आदम (अलैहिस्सलाम) को मिट्टी से बनाया और उनमें अपनी रूह फूंकी। वह धरती के पहले इंसान और पहले पैगंबर थे। अल्लाह ने आदम को हर चीज़ के नाम सिखाए और फिर फ़रिश्तों को आदेश दिया कि उन्हें सजदा करें। सभी फ़रिश्तों ने आदर से सजदा किया, लेकिन इबलीस (शैतान) ने घमंड किया और सजदा करने से इनकार कर दिया। अपने घमंड के कारण इबलीस हमेशा के लिए अल्लाह की रहमत से दूर कर दिया गया।\n\nहज़रत आदम और उनकी पत्नी हव्वा जन्नत में रहने लगे। वे किसी भी पेड़ के फल खा सकते थे सिवाय एक के। शैतान ने बार-बार बहकाया जब तक कि उन्होंने उस मना किए गए पेड़ से फल नहीं खा लिया। जैसे ही उन्होंने ऐसा किया, उन्हें बहुत पछतावा हुआ और उन्होंने अल्लाह से दुआ मांगी: 'ऐ हमारे रब! हमने अपनी जानों पर ज़ुल्म किया है, अगर तू हमें माफ़ नहीं करेगा और हम पर रहम नहीं करेगा तो हम नुकसान उठाने वालों में हो जाएंगे।'\n\nअल्लाह बहुत माफ़ करने वाला है, उसने उनकी तौबा कबूल कर ली और उन्हें धरती पर भेजा ताकि वे यहां रहें, मेहनत करें और अल्लाह की इबादत करें। आदम और हव्वा से ही दुनिया के सभी लोग पैदा हुए। आदम (अलैहिस्सलाम) ने अपनी औलाद को नमाज़ पढ़ना, एक-दूसरे से प्यार करना और हर गलती पर तुरंत अल्लाह की तरफ लौटना सिखाया — क्योंकि अल्लाह तौबा करने वालों से प्यार करता है।"
        ),
        Story(
            id = "nuh",
            emoji = "🚢",
            titleEn = "Prophet Nuh",
            titleUr = "حضرت نوح علیہ السلام",
            titleAr = "نبي الله نوح عليه السلام",
            titleHi = "पैगंबर नूह (अलैहिस्सलाम)",
            taglineEn = "The Ark and the Great Flood",
            taglineUr = "کشتی اور عظیم طوفان",
            taglineAr = "السفينة والطوفان العظيم",
            taglineHi = "कश्ती और महान तूफ़ान",
            lessonEn = "Be patient and trust Allah, even when others do not believe.",
            lessonUr = "صبر کرو اور اللہ پر بھروسہ رکھو، چاہے دوسرے نہ مانیں۔",
            lessonAr = "اصبر وتوكل على الله حق التوكل، حتى وإن لم يؤمن بك الآخرون.",
            lessonHi = "सब्र रखो और अल्लाह पर पूरा भरोसा रखो, चाहे दूसरे न मानें।",
            contentEn = "Prophet Nuh (Noah) called his people to worship Allah for nine hundred and fifty long years. He spoke to them gently, then loudly, in private and in public, day and night. Only a few people listened. The rest laughed at him and stayed worshipping idols of stone and wood.\n\nFinally Allah told Nuh that no one else from his people would believe. Allah commanded him to build a huge ark on dry land, far from any sea. People laughed even louder. 'Why build a boat where there is no water?' they mocked. But Nuh kept working, trusting Allah completely. He cut wood, hammered planks, and shaped a massive ship right in the middle of the land.\n\nWhen the ark was ready, Allah sent rain like the world had never seen. Water poured down from the sky and burst out from the ground. Nuh took his believing family and a pair of every kind of animal onto the ark. The flood covered the whole earth, even the highest mountains. But the ark floated safely on the giant waves.\n\nNuh's own son refused to come, saying he would climb a mountain. The water swallowed him along with all the disbelievers. When the rain stopped and the waters went down, the ark rested on Mount Judi. Nuh and the believers stepped off and started a new beginning, worshipping Allah alone.",
            contentUr = "حضرت نوح علیہ السلام نے ساڑھے نو سو سال تک اپنی قوم کو اللہ کی عبادت کی طرف بلایا۔ آپ نے انہیں دن رات، چپکے سے بھی اور کھل کر بھی، نرمی سے بھی اور بلند آواز سے بھی دعوت دی۔ بس چند لوگ ایمان لائے، باقی سب آپ کا مذاق اڑاتے رہے اور پتھر اور لکڑی کے بتوں کی پوجا میں لگے رہے۔\n\nآخر اللہ نے نوح کو خبر دی کہ اب ان کی قوم میں سے کوئی اور ایمان نہیں لائے گا۔ اللہ نے انہیں حکم دیا کہ خشک زمین پر، سمندر سے بہت دور، ایک بہت بڑی کشتی بنائیں۔ لوگ اور زیادہ ہنسنے لگے: 'بھلا جہاں پانی ہی نہیں وہاں کشتی کیوں بناتے ہو؟' لیکن نوح اللہ پر مکمل بھروسہ رکھتے ہوئے کام کرتے رہے۔ آپ لکڑی کاٹتے، تختے جوڑتے اور بیچ خشکی میں ایک عظیم کشتی تیار کرتے رہے۔\n\nجب کشتی تیار ہوئی، اللہ نے ایسی بارش بھیجی جو پہلے کبھی نہ ہوئی تھی۔ پانی آسمان سے برسا اور زمین سے بھی پھوٹ پڑا۔ نوح نے اپنے ایمان والے گھر والوں اور ہر جانور کے ایک ایک جوڑے کو کشتی میں سوار کر لیا۔ طوفان نے پوری زمین کو ڈھانپ لیا، یہاں تک کہ اونچے پہاڑ بھی ڈوب گئے، لیکن کشتی بڑی بڑی موجوں پر محفوظ تیرتی رہی۔\n\nنوح کا اپنا بیٹا کشتی میں آنے سے انکار کر کے کہنے لگا کہ میں پہاڑ پر چڑھ جاؤں گا، مگر پانی نے اسے اور سب کافروں کو نگل لیا۔ جب بارش رک گئی اور پانی اترا، کشتی جودی پہاڑ پر ٹھہر گئی۔ نوح اور ایمان والے کشتی سے اترے اور ایک نئی شروعات کی، صرف اللہ کی عبادت کے ساتھ۔",
            contentAr = "دعا نبي الله نوح عليه السلام قومه إلى عبادة الله وحده تسعمائة وخمسين سنة. دعاهم بالليل والنهار، سراً وعلانية، برفق ولين، فلم يؤمن معه إلا قليل، بينما سخر منه الآخرون واستمروا في عبادة أصنام الحجر والخشب.\n\nأوحي الله إلى نوح أنه لن يؤمن من قومه إلا من قد آمن، وأمره ببناء سفينة ضخمة على اليابسة بعيداً عن أي بحر. زادت سخرية القوم قائلين: 'كيف تبني سفينة في صحراء لا ماء فيها؟' لكن نوحاً استمر في عمله واثقاً بأمر ربه، يقطع الخشب ويصنع السفينة العظيمة.\n\nعندما اكتملت السفينة، أرسل الله مطراً غزيراً وفجّر الأرض عيوناً. ركب نوح مع المؤمنين وحمل من كل زوجين اثنين من الحيوانات. غطى الطوفان الأرض كلها حتى قمم الجبال العالية، لكن السفينة أبحرت بأمان فوق الأمواج العاتية.\n\nرفض ابن نوح الركوب وقال سآوي إلى جبل يعصمني من الماء، فغرق مع الكافرين. وعندما توقف المطر واستقرت السفينة على جبل الجودي، نزل نوح والمؤمنون ليبدأوا حياة جديدة قائمة على التوحيد وعبادة الله وحده.",
            contentHi = "हज़रत नूह (अलैहिस्सलाम) ने साढ़े नौ सौ साल तक अपनी कौम को अल्लाह की इबादत की तरफ बुलाया। उन्होंने दिन-रात, छिपकर और खुले तौर पर, नरमी से और ज़ोर से लोगों को समझाया। बस कुछ ही लोग ईमान लाए, बाकी सब उनका मज़ाक उड़ाते रहे और पत्थर और लकड़ी की मूर्तियों की पूजा करते रहे।\n\nआखिरकार अल्लाह ने नूह को बताया कि अब उनकी कौम में से कोई और ईमान नहीं लाएगा। अल्लाह ने उन्हें हुक्म दिया कि सूखी ज़मीन पर, समुद्र से बहुत दूर, एक बहुत बड़ी कश्ती बनाएं। लोग और ज़्यादा हंसने लगे: 'भला जहाँ पानी ही नहीं वहाँ कश्ती क्यों बना रहे हो?' लेकिन नूह अल्लाह पर पूरा भरोसा रखते हुए काम करते रहे और एक विशाल कश्ती तैयार कर ली।\n\nजब कश्ती तैयार हुई, तो अल्लाह ने ऐसी बारिश भेजी जो दुनिया में पहले कभी नहीं हुई थी। आसमान से पानी बरसा और ज़मीन से भी पानी फूट पड़ा। नूह ने अपने ईमान वाले परिवार और हर जानवर के एक-एक जोड़े को कश्ती में सवार कर लिया। तूफ़ान ने पूरी धरती को ढंक लिया, यहाँ तक कि ऊँचे पहाड़ भी डूब गए, लेकिन कश्ती बड़ी-बड़ी लहरों पर सुरक्षित तैरती रही।\n\nनूह का अपना बेटा कश्ती में आने से इनकार करके कहने लगा कि मैं पहाड़ पर चढ़ जाऊंगा, मगर पानी ने उसे और सभी काफ़िरों को डुबो दिया। जब बारिश रुकी और पानी उतरा, तो कश्ती जूदी पहाड़ पर ठहर गई। नूह और ईमान वाले कश्ती से उतरे और सिर्फ़ अल्लाह की इबादत के साथ एक नई शुरुआत की।"
        ),
        Story(
            id = "ibrahim",
            emoji = "🔥",
            titleEn = "Prophet Ibrahim",
            titleUr = "حضرت ابراہیم علیہ السلام",
            titleAr = "نبي الله إبراهيم عليه السلام",
            titleHi = "पैगंबर इब्राहिम (अलैहिस्सलाम)",
            taglineEn = "The Friend of Allah",
            taglineUr = "خلیل اللہ",
            taglineAr = "خليل الرحمن",
            taglineHi = "खलील-उल्लाह (अल्लाह के मित्र)",
            lessonEn = "True faith stays strong, even in the hardest test.",
            lessonUr = "سچا ایمان مشکل ترین آزمائش میں بھی مضبوط رہتا ہے۔",
            lessonAr = "الإيمان الصادق يثبت أمام أصعب المحن والاختبارات.",
            lessonHi = "सच्चा ईमान सबसे कठिन परीक्षा में भी मज़बूत रहता है।",
            contentEn = "Prophet Ibrahim (Abraham) lived among people who worshipped statues of stone and wood. Even his own father, Azar, carved idols and sold them. But from a young age Ibrahim knew that statues could not hear, see, eat, or help anyone. He believed in only one true God — Allah — the Creator of the sun, the moon, and the stars.\n\nIbrahim politely asked his father, his uncles, and the king to leave the worship of idols and worship Allah alone. They became angry. So one day, while everyone was away at a big festival, Ibrahim went into the temple. He broke every idol with an axe — except the biggest one — and hung the axe on its shoulder.\n\nWhen the people returned and saw their broken idols, they were furious. They demanded, 'Who did this to our gods?' Ibrahim calmly said, 'Ask the big one — if it can speak!' The people stood quiet for a moment, realizing that statues truly could do nothing. But instead of believing, they grew even more angry. They built the biggest fire anyone had ever seen and threw Ibrahim into it.\n\nAt that moment Allah commanded, 'O fire, be coolness and safety upon Ibrahim.' The flames could not burn him. He walked out completely unharmed, while the disbelievers stood in shock.\n\nIbrahim spent the rest of his life teaching tawhid — that Allah is One. He traveled with his son Ismail to Makkah and together they built the holy Kaaba. Allah loved Ibrahim so much that He called him 'Khalilullah' — the Friend of Allah.",
            contentUr = "حضرت ابراہیم علیہ السلام ایسے لوگوں میں رہتے تھے جو پتھر اور لکڑی کے بتوں کی پوجا کرتے تھے۔ ان کے اپنے والد آزر بھی بت تراش کر بیچتے تھے۔ مگر ابراہیم بچپن سے جانتے تھے کہ یہ بت نہ سن سکتے ہیں، نہ دیکھ سکتے ہیں، نہ کھا سکتے ہیں اور نہ کسی کا کچھ بھلا کر سکتے ہیں۔ آپ صرف ایک سچے معبود — اللہ — پر ایمان رکھتے تھے، جو سورج، چاند اور ستاروں کا خالق ہے۔\n\nابراہیم نے اپنے والد، چچا اور بادشاہ سے بڑے ادب سے کہا کہ بتوں کی پوجا چھوڑ کر صرف اللہ کی عبادت کریں۔ وہ سب غصے میں آ گئے۔ ایک دن جب سب لوگ بڑے میلے میں چلے گئے تو ابراہیم بت خانے میں گئے اور کلہاڑی سے ہر چھوٹے بت کو توڑ ڈالا، صرف بڑے بت کو چھوڑ دیا اور کلہاڑی اسی کے کندھے پر لٹکا دی۔\n\nجب لوگ واپس آئے اور ٹوٹے ہوئے بت دیکھے تو غصے سے بپھر گئے۔ پوچھنے لگے: 'یہ کس نے کیا؟' ابراہیم نے سکون سے فرمایا: 'بڑے بت سے پوچھ لو، اگر یہ بول سکتا ہے!' ایک لمحے کو سب خاموش ہو گئے کہ واقعی بت کچھ نہیں کر سکتے، مگر ماننے کے بجائے اور بھڑک اٹھے۔ انہوں نے ایک بہت بڑی آگ جلائی اور ابراہیم کو اس میں پھینک دیا۔\n\nاسی لمحے اللہ نے حکم دیا: 'اے آگ! ابراہیم پر ٹھنڈی اور سلامتی والی ہو جا۔' آگ انہیں جلا نہ سکی، آپ بالکل صحیح سلامت باہر نکل آئے اور کافر حیران رہ گئے۔\n\nباقی پوری زندگی ابراہیم نے توحید کا درس دیا۔ آپ اپنے بیٹے اسماعیلؑ کے ساتھ مکہ تشریف لے گئے اور دونوں نے مل کر بیت اللہ (کعبہ) کی تعمیر کی۔ اللہ کو ابراہیم اتنے پیارے تھے کہ اس نے انہیں 'خلیل اللہ' — اللہ کا دوست — کہا۔",
            contentAr = "عاش إبراهيم عليه السلام وسط قوم يعبدون الأصنام المصنوعة من الحجر والخشب، وكان والده آزر ينحت تلك الأصنام ويبيعها. لكن إبراهيم أدرك منذ صغره أن هذه الأصنام لا تسمع ولا تبصر ولا تنفع ولا تضر، وآمن بالله الواحد الأحد، خالق الشمس والقمر والنجوم.\n\nدعا إبراهيم والده وقومه بالحكمة واللين لترك الأصنام وعبادة الله، فغضبوا منه. وفي أحد أيام عيدهم، دخل إبراهيم المعبد وحطم كل الأصنام بفأس إلا كبيرهم، وعلق الفأس على كتفه.\n\nفلما عاد القوم ورأوا أصنامهم محطمة غضبوا وقالوا: 'من فعل هذا بآلهتنا؟' أجاب إبراهيم بهدوء: 'اسألوا كبيرهم هذا إن كانوا ينطقون!' أدرك القوم في أنفسهم عجز أصنامهم، لكن كبرياءهم دفعهم لإشعال نار عظيمة وإلقاء إبراهيم فيها.\n\nحينها أمر الله تعالى: 'يَا نَارُ كُونِي بَرْداً وَسَلَاماً عَلَى إِبْرَاهِيمَ'. فلم تحرق النار سوى قيوده، وخرج منها سليماً معافى وسط ذهول الكافرين.\n\nقضى إبراهيم حياته يدعو إلى التوحيد، وسافر مع ابنه إسماعيل إلى مكة وبنيا معاً الكعبة المشرفة. وقد أحبه الله حباً شديداً واتخذه خليلاً.",
            contentHi = "हज़रत इब्राहिम (अलैहिस्सलाम) ऐसे लोगों के बीच रहते थे जो पत्थर और लकड़ी की मूर्तियों की पूजा करते थे। उनके पिता आज़र भी मूर्तियाँ बनाते और बेचते थे। लेकिन इब्राहिम बचपन से जानते थे कि मूर्तियाँ न सुन सकती हैं, न देख सकती हैं, न खा सकती हैं और न किसी की मदद कर सकती हैं। वह सिर्फ़ एक सच्चे ईश्वर — अल्लाह — पर ईमान रखते थे, जो सूरज, चाँद और सितारों का बनाने वाला है।\n\nइब्राहिम ने अपने पिता और राजा से बहुत अदब से कहा कि मूर्तियों की पूजा छोड़कर सिर्फ़ अल्लाह की इबादत करें। वे सब गुस्सा हो गए। एक दिन जब सभी लोग एक बड़े मेले में गए हुए थे, तो इब्राहिम मंदिर में गए और कुल्हाड़ी से हर छोटी मूर्ति को तोड़ दिया, सिर्फ़ बड़ी मूर्ति को छोड़ दिया और कुल्हाड़ी उसी के कंधे पर टाँग दी।\n\nजब लोग वापस आए और टूटी हुई मूर्तियाँ देखीं तो बहुत गुस्सा हुए। उन्होंने पूछा: 'हमारी मूर्तियों के साथ ऐसा किसने किया?' इब्राहिम ने शांति से कहा: 'बड़ी मूर्ति से पूछ लो, अगर यह बोल सकती है!' एक पल के लिए सब चुप हो गए कि मूर्तियाँ वास्तव में कुछ नहीं कर सकतीं, मगर मानने के बजाय और भड़क उठे। उन्होंने एक बहुत बड़ी आग जलाई और इब्राहिम को उसमें फेंक दिया।\n\nउसी समय अल्लाह ने आदेश दिया: 'ऐ आग! इब्राहिम पर ठंडी और सुरक्षा वाली हो जा।' आग उन्हें जला नहीं सकी, वह बिल्कुल सुरक्षित बाहर निकल आए और काफ़िर हैरान रह गए।\n\nइब्राहिम ने अपना पूरा जीवन अल्लाह की एकता (तौहीद) का संदेश देने में बिताया। वह अपने बेटे इस्माइल के साथ मक्का गए और दोनों ने मिलकर पवित्र काबा का निर्माण किया। अल्लाह को इब्राहिम इतने प्यारे थे कि उसने उन्हें 'खलील-उल्लाह' (अल्लाह का मित्र) कहा।"
        ),
        Story(
            id = "yusuf",
            emoji = "🌙",
            titleEn = "Prophet Yusuf",
            titleUr = "حضرت یوسف علیہ السلام",
            titleAr = "نبي الله يوسف عليه السلام",
            titleHi = "पैगंबर यूसुफ (अलैहिस्सलाम)",
            taglineEn = "The Boy Who Interpreted Dreams",
            taglineUr = "خوابوں کی تعبیر بتانے والے",
            taglineAr = "مفسر الأحلام والصديق الأمين",
            taglineHi = "सपनों का अर्थ बताने वाले",
            lessonEn = "Allah's plan is always better — even when things feel unfair.",
            lessonUr = "اللہ کا منصوبہ ہمیشہ بہتر ہوتا ہے، چاہے ابھی بات مشکل لگے۔",
            lessonAr = "تدبير الله دائماً أفضل، مهما بدت الظروف صعبة ومؤلمة.",
            lessonHi = "अल्लाह की योजना हमेशा बेहतर होती है, चाहे अभी परिस्थितियाँ कठिन लगें।",
            contentEn = "Prophet Yusuf (Joseph) was the beloved son of Prophet Yaqub. As a young boy, Yusuf had a beautiful dream — eleven stars, the sun, and the moon all bowed down to him. His wise father told him not to tell his brothers, because they would become jealous.\n\nYusuf's eleven brothers were already jealous of how much their father loved him. They made a wicked plan: they took Yusuf far away and threw him into a deep, dark well. Then they put fake blood on his shirt and told their father a wolf had eaten him.\n\nA passing caravan stopped to draw water and found Yusuf in the well. They sold him as a slave in Egypt to a nobleman called Al-Aziz. Yusuf grew up strong, handsome, and incredibly honest. When the nobleman's wife tried to lead him into wrong, Yusuf refused and ran. He was wrongly thrown into prison — yet even there he taught the other prisoners about Allah.\n\nAllah gave Yusuf a special gift: he could interpret dreams. In prison, he correctly told two men what their dreams meant. Years later, the King of Egypt had a strange dream about seven fat cows being eaten by seven thin cows. Yusuf explained: seven years of good harvest would come, followed by seven years of famine. He told them to save grain.\n\nThe king was so impressed he made Yusuf the chief minister of Egypt. When the famine came, people from many lands traveled to Egypt for food. One day, his own brothers came begging — not recognizing the brother they had thrown into a well. Yusuf forgave them with tears, brought his whole family to Egypt, and his childhood dream finally came true.",
            contentUr = "حضرت یوسف علیہ السلام حضرت یعقوبؑ کے بہت پیارے بیٹے تھے۔ بچپن میں یوسف نے ایک خوبصورت خواب دیکھا کہ گیارہ ستارے، سورج اور چاند ان کو سجدہ کر رہے ہیں۔ ان کے دانا والد نے فرمایا: یہ خواب اپنے بھائیوں کو نہ بتانا، ورنہ وہ حسد کریں گے۔\n\nیوسف کے گیارہ بھائی پہلے ہی اپنے والد کی محبت پر جلتے تھے۔ انہوں نے بری چال چلی: یوسف کو دور لے گئے اور ایک گہرے، اندھیرے کنویں میں ڈال دیا۔ پھر ان کی قمیض پر جھوٹا خون لگا کر والد کو کہا کہ بھیڑیا کھا گیا۔\n\nایک قافلہ پانی بھرنے رکا اور یوسف کو کنویں سے نکال لیا۔ انہوں نے یوسف کو مصر میں ایک امیر شخص 'العزیز' کے ہاتھ غلام بنا کر بیچ دیا۔ یوسف بڑے ہوئے تو خوبصورت، طاقتور اور بہت سچے انسان تھے۔ جب عزیز کی بیوی نے انہیں برائی پر مجبور کرنا چاہا تو آپ نے انکار کیا اور بھاگ نکلے۔ اس پر آپ کو بے قصور جیل میں ڈال دیا گیا، مگر وہاں بھی آپ دوسرے قیدیوں کو اللہ کا پیغام دیتے رہے۔\n\nاللہ نے یوسف کو خوابوں کی تعبیر کا خاص علم دیا تھا۔ جیل میں دو قیدیوں کے خوابوں کی صحیح تعبیر بتائی۔ کئی سال بعد بادشاہِ مصر نے ایک عجیب خواب دیکھا کہ سات موٹی گائیں ہیں اور سات دبلی گائیں انہیں کھا رہی ہیں۔ یوسف نے سمجھایا: 'سات سال خوب فصل ہو گی، پھر سات سال قحط آئے گا، اس لیے اناج جمع کرو۔'\n\nبادشاہ اتنا متاثر ہوا کہ یوسف کو پورے مصر کا وزیرِ خزانہ بنا دیا۔ جب قحط آیا تو دور دور سے لوگ مصر اناج لینے آنے لگے۔ ایک دن ان کے اپنے بھائی بھی غلہ لینے آئے — انہیں پہچانے بغیر جنہیں انہوں نے کنویں میں ڈالا تھا۔ یوسف نے آنسوؤں کے ساتھ سب کو معاف کیا، اپنے سب گھر والوں کو مصر بلا لیا، اور بچپن کا خواب پورا ہو گیا۔",
            contentAr = "كان يوسف عليه السلام الابن المحبب ليعقوب عليه السلام. رأى في صغره رؤيا عجيبة: أحد عشر كوكباً والشمس والقمر يسجدون له. أدرك أبوه يعقوب عظم الرؤيا ونصح يوسف بألا يقصها على إخوته خوفاً من حسدهم.\n\nاشتعل الحسد في قلوب إخوة يوسف، فدبروا مكيدة وألقوه في بئر مظلمة، ثم عادوا إلى أبيهم بقميصه ملطخاً بدم كذب مدعين أن الذئب قد أكله.\n\nمرت قافلة بالبئر فأخرجوا يوسف وباعوه في مصر للوزير (العزيز). نشأ يوسف شاباً في غاية الجمال والأمانة. وعندما راودته امرأة العزيز عن نفسه رفض واعتصم بالله، فأُدخل السجن ظلماً، ولكنه استمر هناك يدعو السجناء إلى توحيد الله.\n\nوهب الله يوسف علم تفسير الأحلام. وفي السجن فسر رؤيا سجينين بصدق. وبعد سنوات رأى ملك مصر رؤيا غريبة عن سبع بقرات سمان يأكلهن سبع عجاف. فسر يوسف الرؤيا بأن البلاد ستشهد سبع سنوات من الخصب تليها سبع سنوات من الجفاف الشديد، ونصحهم بطريقة حفظ الغلال.\n\nأعجب الملك بحكمة يوسف وعينه أميناً على خزائن مصر. وعندما حل الجفاف، جاء إخوة يوسف يطلبون الطعام دون أن يعرفوه. كشف يوسف عن نفسه وعفا عنهم عفواً كريماً، وجمع شمل الأسرة في مصر، وتحققت رؤياه التي رآها في صغره.",
            contentHi = "हज़रत यूसुफ (अलैहिस्सलाम) पैगंबर याकूब के बहुत प्यारे बेटे थे। बचपन में यूसुफ ने एक खूबसूरत सपना देखा कि ग्यारह तारे, सूरज और चाँद उन्हें सजदा कर रहे हैं। उनके बुद्धिमान पिता ने कहा कि यह सपना अपने भाइयों को मत बताना, वरना वे जलन करेंगे।\n\nयूसुफ के ग्यारह भाई पहले से ही अपने पिता के प्यार से जलते थे। उन्होंने एक बुरी योजना बनाई: वे यूसुफ को दूर ले गए और एक गहरे, अंधेरे कुएँ में फेंक दिया। फिर उनकी कमीज़ पर झूठा खून लगाकर पिता से कहा कि भेड़िया खा गया।\n\nएक गुज़रते हुए काफ़िले ने पानी भरने के लिए कुएँ में बाल्टी डाली और यूसुफ को बाहर निकाल लिया। उन्होंने यूसुफ को मिस्र के एक अमीर मंत्री 'अल-अज़ीज़' को गुलाम बनाकर बेच दिया। यूसुफ बड़े हुए तो बहुत सुंदर और ईमानदार थे। जब मंत्री की पत्नी ने उन्हें बुराई की ओर ले जाना चाहा तो उन्होंने इनकार किया। उन्हें बेगुनाह जेल में डाल दिया गया, लेकिन वहाँ भी वह दूसरे कैदियों को अल्लाह का संदेश देते रहे।\n\nअल्लाह ने यूसुफ को सपनों का अर्थ (तअबीर) बताने का विशेष ज्ञान दिया था। जेल में दो कैदियों के सपनों का सही अर्थ बताया। कई साल बाद मिस्र के राजा ने एक अजीब सपना देखा कि सात मोटी गायें हैं और सात दुबली गायें उन्हें खा रही हैं। यूसुफ ने समझाया: 'सात साल बहुत अच्छी फ़सल होगी, फिर सात साल अकाल पड़ेगा, इसलिए अनाज जमा करो।'\n\nराजा इतना प्रभावित हुआ कि उसने यूसुफ को पूरे मिस्र का खज़ांची (वित्त मंत्री) बना दिया। जब अकाल पड़ा तो दूर-दूर से लोग अनाज लेने आने लगे। एक दिन उनके अपने भाई भी अनाज लेने आए — बिना पहचाने कि यह वही भाई है जिसे कुएँ में फेंका था। यूसुफ ने आँसुओं के साथ सबको माफ़ कर दिया, अपने पूरे परिवार को मिस्र बुला लिया, और बचपन का सपना पूरा हो गया।"
        ),
        Story(
            id = "musa",
            emoji = "🌊",
            titleEn = "Prophet Musa",
            titleUr = "حضرت موسیٰ علیہ السلام",
            titleAr = "نبي الله موسى عليه السلام",
            titleHi = "पैगंबर मूसा (अलैहिस्सलाम)",
            taglineEn = "The Sea That Split in Two",
            taglineUr = "سمندر جو دو حصوں میں چِر گیا",
            taglineAr = "انشقاق البحر وعصا الحق",
            taglineHi = "समुद्र जो दो हिस्सों में बँट गया",
            lessonEn = "Allah saves the believers, no matter how powerful the enemy.",
            lessonUr = "اللہ ایمان والوں کو بچا لیتا ہے، چاہے دشمن کتنا ہی طاقتور ہو۔",
            lessonAr = "الله ينصر المؤمنين ويدافع عنهم مهما بلغت قوة العدو وجبروته.",
            lessonHi = "अल्लाह ईमान वालों को बचा लेता है, चाहे दुश्मन कितना भी शक्तिशाली हो।",
            contentEn = "Prophet Musa (Moses) was born at a time when the cruel Pharaoh ruled Egypt. Pharaoh was so afraid of losing power that he ordered all Israelite baby boys to be harmed. Musa's mother was heartbroken. Allah inspired her to place baby Musa in a basket and let it float down the Nile river.\n\nAmazingly, the basket floated right to the Pharaoh's palace. The Pharaoh's wife loved the baby at once and convinced Pharaoh to keep him. Allah even arranged for Musa's own mother to be brought as his nurse — so the very enemy who feared him raised him in his own home.\n\nWhen Musa grew up, Allah spoke to him directly on Mount Tur and gave him the mission to free the Israelites and call Pharaoh to worship Allah. Pharaoh refused and called his magicians to embarrass Musa. The magicians threw their ropes and they looked like wriggling snakes. Then Musa threw his staff — it became a real snake and swallowed all of theirs. The magicians fell into sujood right away, saying, 'We believe in the Lord of Musa and Harun!'\n\nPharaoh became even more stubborn. So Allah sent many warnings — locusts, frogs, blood, and storms — but Pharaoh still refused. Finally Musa led the Israelites out of Egypt in the dead of night. Pharaoh's huge army chased after them and trapped them at the Red Sea.\n\nThe people were terrified. Musa said calmly, 'Never! My Lord is with me; He will guide me.' Allah commanded him to strike the sea with his staff. The water split into two huge walls, and a dry path appeared. The believers walked safely across. When Pharaoh's army followed onto the dry path, the walls of water crashed down and drowned every last one of them.",
            contentUr = "حضرت موسیٰ علیہ السلام اس وقت پیدا ہوئے جب ظالم فرعون مصر پر حکومت کرتا تھا۔ فرعون کو تخت چھن جانے کا اتنا ڈر تھا کہ اس نے بنی اسرائیل کے ہر نوزائیدہ بیٹے کو قتل کرنے کا حکم دے رکھا تھا۔ موسیٰ کی والدہ بہت پریشان تھیں۔ اللہ نے ان کے دل میں ڈالا کہ ننھے موسیٰ کو ایک صندوق میں ڈال کر دریائے نیل میں بہا دیں۔\n\nحیرت انگیز طور پر صندوق سیدھا فرعون کے محل پہنچ گیا۔ فرعون کی بیوی کو بچہ بہت پسند آیا اور اس نے فرعون کو راضی کیا کہ بچے کو پال لیں۔ اللہ نے ایسا انتظام کیا کہ موسیٰ کی اپنی والدہ ہی کو ان کی دایہ بنا دیا گیا — یوں جس دشمن کو ان کا ڈر تھا، اسی نے اپنے گھر میں ان کی پرورش کی۔\n\nجب موسیٰ بڑے ہوئے تو اللہ نے کوہِ طور پر براہِ راست ان سے کلام کیا اور انہیں یہ ذمہ داری دی کہ بنی اسرائیل کو فرعون کی غلامی سے آزاد کرائیں اور فرعون کو اللہ کی عبادت کی دعوت دیں۔ فرعون نے انکار کر کے جادوگر بلائے تاکہ موسیٰ کو شرمندہ کریں۔ جادوگروں نے رسیاں پھینکیں جو سانپ کی طرح لگنے لگیں۔ موسیٰ نے اپنا عصا پھینکا تو وہ سچ مچ کا اژدہا بن گیا اور سب جادو نگل گیا۔ جادوگر فوراً سجدے میں گر پڑے اور کہنے لگے: 'ہم موسیٰ اور ہارون کے رب پر ایمان لائے!'\n\nفرعون اور سرکش ہو گیا، چنانچہ اللہ نے کئی نشانیاں بھیجیں — ٹڈیاں، مینڈک، خون اور طوفان — مگر فرعون نہ مانا۔ آخر موسیٰ نے رات کے اندھیرے میں بنی اسرائیل کو مصر سے نکالا۔ فرعون کا بہت بڑا لشکر پیچھے دوڑا اور بحرِ احمر کے کنارے انہیں جا لیا۔\n\nلوگ گھبرا گئے، مگر موسیٰ نے یقین سے کہا: 'ہرگز نہیں! میرا رب میرے ساتھ ہے، وہ ضرور رہنمائی کرے گا۔' اللہ نے حکم دیا کہ سمندر کو عصا سے ماریں۔ پانی دو بلند دیواروں کی طرح پھٹ گیا اور بیچ میں خشک راستہ بن گیا۔ ایمان والے بحفاظت پار اتر گئے۔ جب فرعون کا لشکر اسی راستے پر آیا تو پانی کی دیواریں ملیں اور سب کو غرق کر دیا۔",
            contentAr = "ولد موسى عليه السلام في زمن فرعون الطاغية الذي أمر بقتل كل مولود ذكر من بني إسرائيل. ألهم الله أم موسى أن تضعه في تابوت وتلقيه في نهر النيل حماية له.\n\nساق النيل التابوت قريباً من قصر فرعون، فأخذته آسيا زوجة فرعون وأحبته وأقنعت فرعون بتربيته. ورد الله موسى إلى أمه لتكون مرضعة له، فتربى في بيت عدوه وهو في أمان الله.\n\nلما كبر موسى كلمه الله عند جبل الطور وأرسله إلى فرعون ليدعوه إلى التوحيد ويحرر بني إسرائيل. استكبر فرعون وجمع السحرة لمواجهة موسى. ألقى السحرة حبالهم فخيل للناس أنها ثعابين، فألقى موسى عصاه فتحولت إلى ثعبان حقيقي ابتلع سحرهم. خر السحرة سجداً وقالوا: 'آمَنَّا بِرَبِّ هَارُونَ وَمُوسَى'.\n\nزاد عناد فرعون، فأرسل الله عليهم آيات مفصلات: الطوفان والجراد والقمل والضفادع والدم، لكن فرعون أصر على كفره. خرج موسى بالمؤمنين ليلاً، فلحقهم فرعون بجيشه العرمرم عند البحر الأحمر.\n\nخاف القوم وقالوا إنا لمدركون، فقال موسى بثقة المؤمن: 'كَلَّا إِنَّ مَعِيَ رَبِّي سَيَهْدِينِ'. ضرب موسى البحر بعصاه فانفلق فكان كل فرق كالطود العظيم، وظهر طريق يابس عبر منه المؤمنون. ولما دخل فرعون وجيشه أطبق البحر عليهم فغرقوا جميعاً.",
            contentHi = "हज़रत मूसा (अलैहिस्सलाम) उस समय पैदा हुए जब ज़ालिम फ़िरऔन मिस्र पर शासन करता था। फ़िरऔन को अपना सिंहासन छिन जाने का इतना डर था कि उसने बनी इस्राइल के हर नवजात लड़के को मारने का आदेश दे रखा था। मूसा की माँ बहुत परेशान थीं। अल्लाह ने उनके दिल में डाला कि नन्हे मूसा को एक संदूक में रखकर नील नदी में बहा दें।\n\nआश्चर्यजनक रूप से संदूक सीधा फ़िरऔन के महल पहुँच गया। फ़िरऔन की पत्नी को बच्चा बहुत पसंद आया और उसने फ़िरऔन को राज़ी किया कि बच्चे को पाल लें। अल्लाह ने ऐसा इंतज़ाम किया कि मूसा की अपनी माँ को ही उनकी दाई बना दिया गया — इस तरह जिस दुश्मन से उनका डर था, उसी ने अपने घर में उनका पालन-पोषण किया।\n\nजब मूसा बड़े हुए तो अल्लाह ने कोह-ए-तूर (तूर पर्वत) पर सीधे उनसे बात की और उन्हें यह ज़िम्मेदारी दी कि बनी इस्राइल को फ़िरऔन की गुलामी से आज़ाद कराएँ और फ़िरऔन को अल्लाह की इबादत का निमंत्रण दें। फ़िरऔन ने इनकार करके जादूगर बुलाए ताकि मूसा को नीचा दिखा सके। जादूगरों ने रस्सियाँ फेंकीं जो साँप की तरह लगने लगीं। मूसा ने अपनी लाठी (असा) फेंकी तो वह असली अजगर बन गई और सारा जादू निगल गई। जादूगर तुरंत सजदे में गिर पड़े और कहने लगे: 'हम मूसा और हारून के रब पर ईमान लाए!'\n\nफ़िरऔन और ज़्यादा घमंडी हो गया, इसलिए अल्लाह ने कई चेतावनियाँ भेजीं — टिड्डियाँ, मेंढक, खून और तूफ़ान — मगर फ़िरऔन नहीं माना। आखिरकार मूसा रात के अँधेरे में बनी इस्राइल को मिस्र से निकाल ले गए। फ़िरऔन का बहुत बड़ा लश्कर पीछे दौड़ा और लाल सागर के किनारे उन्हें घेर लिया।\n\nलोग घबरा गए, मगर मूसा ने पूरे विश्वास से कहा: 'हरगिज़ नहीं! मेरा रब मेरे साथ है, वह ज़रूर रास्ता दिखाएगा।' अल्लाह ने आदेश दिया कि समुद्र को लाठी से मारें। पानी दो ऊँची दीवारों की तरह फट गया और बीच में सूखा रास्ता बन गया। ईमान वाले सुरक्षित पार हो गए। जब फ़िरऔन का लश्कर उसी रास्ते पर आया तो पानी की दीवारें मिल गईं और सभी डूब गए।"
        ),
        Story(
            id = "yunus",
            emoji = "🐟",
            titleEn = "Prophet Yunus",
            titleUr = "حضرت یونس علیہ السلام",
            titleAr = "نبي الله يونس عليه السلام",
            titleHi = "पैगंबर यूनुस (अलैहिस्सलाम)",
            taglineEn = "In the Belly of the Whale",
            taglineUr = "مچھلی کے پیٹ میں",
            taglineAr = "في بطن الحوت والتسبيح المنجي",
            taglineHi = "मछली के पेट में",
            lessonEn = "Whenever you make a mistake, turn back to Allah at once.",
            lessonUr = "جب بھی غلطی ہو، فوراً اللہ کی طرف لوٹ آؤ۔",
            lessonAr = "التسبيح والاعتراف بالخطأ ينجيان المؤمن من أحلك الكربات.",
            lessonHi = "जब भी गलती हो, तुरंत अल्लाह की तरफ लौटो और माफ़ी माँगो।",
            contentEn = "Prophet Yunus (Jonah) was sent to the people of a city called Nineveh. He called them to worship Allah alone, but year after year they refused and mocked him. Tired and upset, Yunus left his city before Allah had told him to.\n\nHe boarded a ship sailing far across the sea. A fierce storm came. The waves grew huge and the ship was about to sink. The sailors believed it was too heavy, so they drew lots to decide who should jump into the sea. Yunus's name came out — once, twice, three times. Yunus understood this was from Allah. He jumped into the dark, stormy water.\n\nAt once, a huge whale swallowed him whole. Inside the belly of the whale, in three layers of darkness — the darkness of the night, the darkness of the deep sea, and the darkness of the whale itself — Yunus realized his mistake of leaving his people without permission.\n\nHe cried out from his heart: 'La ilaha illa anta subhanaka inni kuntu minaz-zalimin' — 'There is no god but You. Glory is to You. Truly, I have been of the wrongdoers.'\n\nAllah heard his sincere du'a and forgave him. He commanded the whale to gently release Yunus on a quiet shore. Yunus's body was weak, so Allah grew a soft, shady plant over him to protect him while he healed.\n\nWhen Yunus returned to his city, something amazing had happened. His people had finally seen the truth, repented to Allah, and over a hundred thousand of them now believed. Allah saved them all because of their true tawbah (repentance).",
            contentUr = "حضرت یونس علیہ السلام کو ایک شہر 'نینویٰ' کے لوگوں کی طرف بھیجا گیا۔ آپ انہیں صرف اللہ کی عبادت کی دعوت دیتے رہے، مگر وہ سال در سال انکار اور مذاق کرتے رہے۔ تنگ آ کر یونس اللہ کے حکم سے پہلے ہی شہر چھوڑ کر چل دیے۔\n\nآپ ایک کشتی میں سوار ہوئے جو دور سمندر میں جا رہی تھی۔ ایک خوفناک طوفان آیا، موجیں بلند ہو گئیں اور کشتی ڈوبنے لگی۔ ملاحوں نے سمجھا کہ کشتی زیادہ بھاری ہے، لہٰذا قرعہ ڈالا کہ کون سمندر میں چھلانگ لگائے۔ یونس کا نام بار بار نکلا۔ یونس نے سمجھ لیا کہ یہ اللہ کی طرف سے ہے، اور سمندر میں کود گئے۔\n\nاسی وقت ایک بہت بڑی مچھلی نے انہیں نگل لیا۔ مچھلی کے پیٹ میں، تین تہہ دار اندھیروں میں — رات کا اندھیرا، گہرے سمندر کا اندھیرا اور خود مچھلی کا اندھیرا — یونس کو اپنی غلطی کا احساس ہو گیا کہ انہوں نے اپنی قوم کو اللہ کی اجازت کے بغیر چھوڑا۔\n\nانہوں نے دل کی گہرائی سے پکارا: 'لا الٰہ الا انت سبحانک انی کنت من الظالمین' — تیرے سوا کوئی معبود نہیں، تو پاک ہے، بے شک میں ظالموں میں سے تھا۔\n\nاللہ نے ان کی سچی دعا سنی اور انہیں معاف کر دیا۔ اللہ کے حکم سے مچھلی نے انہیں نرم ساحل پر اتار دیا۔ یونس کا جسم بہت کمزور تھا، اس لیے اللہ نے ان پر ایک نرم سایہ دار بیل اگا دی تاکہ وہ آرام سے صحت یاب ہو سکیں۔\n\nجب یونس واپس اپنے شہر پہنچے تو ایک عجیب منظر تھا۔ ان کی قوم سچ سمجھ چکی تھی اور توبہ کر چکی تھی، اور اب ایک لاکھ سے زیادہ لوگ ایمان لے آئے تھے۔ اللہ نے سب کو ان کی سچی توبہ کی وجہ سے بچا لیا۔",
            contentAr = "أرسل الله يونس عليه السلام إلى أهل نينوى ليدعوهم إلى عبادة الله وحده، لكنهم أصروا على الكفر والسخرية. ضاق يونس بهم ذرعاً فغادر القرية قبل أن يأذن الله له.\n\nركب يونس سفينة في البحر، فهبت عاصفة شديدة وكادت السفينة أن تغرق. قرر الركاب إجراء قرعة لتخفيف الحمل بإلقاء أحدهم في البحر. وقعت القرعة على يونس ثلاث مرات، فأدرك أن هذا أمر من الله، وألقى بنفسه في الأمواج المتلاطمة.\n\nابتلعه حوت عظيم بأمر الله. وفي ظلمات ثلاث — ظلمة الليل، وظلمة قاع البحر، وظلمة بطن الحوت — نادى يونس ربه معترفاً بخطئه قائلاً: 'لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ'.\n\nاستجاب الله دعاءه وأمر الحوت أن يلفظه على شاطئ آمن. أنبت الله عليه شجرة من يقطين تظله وتغذيه حتى استرد عافيته.\n\nلما عاد يونس إلى قومه وجدهم قد آمنوا جميعاً وتابوا إلى الله حين رأوا بوادر العذاب، فمتعهم الله وحفظهم لإيمانهم الصادق.",
            contentHi = "हज़रत यूनुस (अलैहिस्सलाम) को 'नीनवा' शहर के लोगों की तरफ भेजा गया था। वह उन्हें सिर्फ़ अल्लाह की इबादत करने के लिए बुलाते रहे, लेकिन वे साल-दर-साल इनकार करते और मज़ाक उड़ाते रहे। तंग आकर यूनुस अल्लाह के आदेश से पहले ही शहर छोड़कर चले गए।\n\nवह एक जहाज़ में सवार हुए जो दूर समुद्र में जा रहा था। एक भयानक तूफ़ान आया, लहरें ऊँची हो गईं और जहाज़ डूबने लगा। नाविकों ने सोचा कि जहाज़ बहुत भारी है, इसलिए लॉटरी (कुर्रा) डाली कि कौन समुद्र में कूदेगा। यूनुस का नाम बार-बार निकला। यूनुस समझ गए कि यह अल्लाह की तरफ से है, और समुद्र में कूद गए।\n\nउसी समय एक बहुत बड़ी मछली (ह्वेल) ने उन्हें निगल लिया। मछली के पेट में, तीन परतों के अँधेरे में — रात का अँधेरा, गहरे समुद्र का अँधेरा और मछली के पेट का अँधेरा — यूनुस को अपनी गलती का एहसास हो गया कि उन्होंने अपनी कौम को अल्लाह की अनुमति के बिना छोड़ा।\n\nउन्होंने दिल की गहराई से पुकारा: 'ला इलाहा इल्ला अन्ता सुभानका इन्नी कुन्तु मिनज़-ज़ालिमीन' — तेरे सिवा कोई पूज्य नहीं, तू पवित्र है, बेशक मैं ज़ालिमों में से था।\n\nअल्लाह ने उनकी सच्ची दुआ सुनी और उन्हें माफ़ कर दिया। अल्लाह के आदेश से मछली ने उन्हें सुरक्षित किनारे पर उतार दिया। यूनुस का शरीर बहुत कमज़ोर था, इसलिए अल्लाह ने उन पर एक नरम छायादार बेल (लौकी का पौधा) उगा दी ताकि वे आराम से स्वस्थ हो सकें।\n\nजब यूनुस वापस अपने शहर पहुँचे तो एक अद्भुत नज़ारा था। उनकी कौम सच्चाई समझ चुकी थी और तौबा कर चुकी थी, और अब एक लाख से ज़्यादा लोग ईमान ले आए थे। अल्लाह ने सबको उनकी सच्ची तौबा के कारण बचा लिया।"
        ),
        Story(
            id = "sulaiman",
            emoji = "👑",
            titleEn = "Prophet Sulaiman",
            titleUr = "حضرت سلیمان علیہ السلام",
            titleAr = "نبي الله سليمان عليه السلام",
            titleHi = "पैगंबर सुलेमान (अलैहिस्सलाम)",
            taglineEn = "The King Who Spoke with Animals",
            taglineUr = "بادشاہ جو جانوروں سے بات کرتے تھے",
            taglineAr = "الملك الحكيم ومنطق الطير",
            taglineHi = "राजा जो जानवरों से बात करते थे",
            lessonEn = "Power is a gift — use it with humility and gratitude.",
            lessonUr = "طاقت ایک نعمت ہے — اسے انکساری اور شکر کے ساتھ استعمال کرو۔",
            lessonAr = "الملك والقوة نعمة من الله تستوجب الشكر والتواضع.",
            lessonHi = "शक्ति और अधिकार एक वरदान है — इसे विनम्रता और शुक्र के साथ इस्तेमाल करो।",
            contentEn = "Prophet Sulaiman (Solomon) was the son of Prophet Dawud (David). When he was still young, his wisdom amazed everyone. Allah gave him a kingdom no king before or after has ever had: he could understand the language of animals and birds, the wind obeyed his command, and even the jinn worked for him.\n\nOne day, while marching at the head of his huge army, Sulaiman heard a tiny ant on the ground. The ant was calling out to its friends: 'O ants! Get into your homes so Sulaiman and his soldiers don't crush you without realizing.' Sulaiman smiled at her words and prayed, 'My Lord, inspire me to be grateful for the blessings You have given me and my parents, and to do good deeds that please You.'\n\nLater, Sulaiman counted his birds and noticed his messenger, the hoopoe, was missing. When the hoopoe returned, it had news: it had flown to the land of Sheba where a queen ruled, and she and her people were worshipping the sun. Sulaiman sent her a letter inviting her to leave sun-worship and believe in Allah.\n\nWhen the Queen of Sheba decided to visit, Sulaiman asked his court who could bring her throne to him before she arrived. A jinn said, 'I can do it before you stand from your seat.' But a man with knowledge of Allah's name said, 'I can bring it in the blink of an eye.' And he did — the throne appeared instantly.\n\nThe Queen was amazed by the throne, the glass floor she mistook for water, and Sulaiman's humble worship of Allah. She accepted Islam, saying, 'My Lord, I have wronged myself, and I submit with Sulaiman to Allah, the Lord of the worlds.'",
            contentUr = "حضرت سلیمان علیہ السلام حضرت داؤدؑ کے بیٹے تھے۔ ابھی کم عمر تھے کہ ان کی حکمت سب کو حیران کر دیتی تھی۔ اللہ نے انہیں ایسی بادشاہت دی جیسی نہ ان سے پہلے کسی کو ملی نہ بعد میں: وہ جانوروں اور پرندوں کی زبان سمجھتے تھے، ہوا ان کے حکم میں تھی، اور جنّات تک ان کی خدمت میں لگے تھے۔\n\nایک دن آپ اپنے بہت بڑے لشکر کے ساتھ جا رہے تھے کہ زمین پر ایک چھوٹی سی چیونٹی کی آواز سنی۔ وہ اپنی ساتھیوں کو پکار رہی تھی: 'اے چیونٹیو! اپنے گھروں میں گھس جاؤ، کہیں سلیمان اور اس کا لشکر تمہیں بے خیالی میں کچل نہ ڈالے۔' سلیمان اس کی بات پر مسکرا اٹھے اور دعا کی: 'اے میرے رب! مجھے توفیق دے کہ میں تیری اور میرے والدین پر کی گئی نعمتوں کا شکر کروں اور ایسے نیک عمل کروں جو تجھے پسند ہوں۔'\n\nبعد میں سلیمان نے اپنے پرندوں کا جائزہ لیا تو اپنے پیغام رساں ہدہد کو غائب پایا۔ جب ہدہد لوٹا تو ایک خبر لے کر آیا: وہ سبا کی سرزمین تک گیا تھا، جہاں ایک ملکہ حکومت کرتی ہے اور وہ اور اس کی قوم سورج کو پوجتے ہیں۔ سلیمان نے ایک خط بھیجا اور انہیں سورج کی پوجا چھوڑ کر اللہ پر ایمان لانے کی دعوت دی۔\n\nجب ملکہ سبا ملاقات کے لیے آنے لگی تو سلیمان نے درباریوں سے پوچھا کہ ملکہ کے آنے سے پہلے اس کا تخت کون لا سکتا ہے؟ ایک جن نے کہا: 'میں اس سے پہلے لا دوں گا کہ آپ اپنی جگہ سے اٹھیں۔' مگر ایک شخص جس کے پاس اللہ کے اسم کا علم تھا، کہنے لگا: 'میں آنکھ جھپکنے سے پہلے لے آؤں گا۔' اور سچ مچ تخت ایک لمحے میں موجود ہو گیا۔\n\nملکہ تخت، شیشے کے فرش (جسے اس نے پانی سمجھا) اور سلیمان کی اللہ کے سامنے عاجزی دیکھ کر حیران رہ گئی۔ اس نے اسلام قبول کر لیا اور کہا: 'اے میرے رب! میں نے اپنی جان پر ظلم کیا، اب میں سلیمان کے ساتھ تمام جہانوں کے رب اللہ پر ایمان لاتی ہوں۔'",
            contentAr = "ورث سليمان عليه السلام النبوة والحكمة عن أبيه داود عليه السلام. وقد وهبه الله ملكاً لا ينبغي لأحد من بعده؛ سخر له الريح تجري بأمره، وعلمه منطق الطير والحيوان، وسخر له الجن يعملون بين يديه.\n\nمر سليمان يوماً بجيشه العظيم على وادي النمل، فسمع نملة تقول: 'يَا أَيُّهَا النَّمْلُ ادْخُلُوا مَسَاكِنَكُمْ لَا يَحْطِمَنَّكُمْ سُلَيْمَانُ وَجُنُودُهُ وَهُمْ لَا يَشْعُرُونَ'. فتبسم ضاحكاً من قولها وشكر الله على نعمه.\n\nوفي أحد الأيام تفقد سليمان الطير فلم يجد الهدهد. فلما عاد الهدهد أخبره أنه وجد مملكة سبأ تحكمهم ملكة ويعبدون الشمس من دون الله. أرسل سليمان كتاباً يدعوهم فيه إلى الإسلام والتسليم لله وحده.\n\nفلما جاءت بلقيس ملكة سبأ، أمر سليمان بإحضار عرشها، فأحضره الذي عنده علم من الكتاب قبل أن يرتد إليه طرفه. تعجبت بلقيس من حكمة سليمان وعظم ملكه وتواضعه لله، وأعلنت إسلامها قائلة: 'رَبِّ إِنِّي ظَلَمْتُ نَفْسِي وَأَسْلَمْتُ مَعَ سُلَيْمَانَ لِلَّهِ رَبِّ الْعَالَمِينَ'.",
            contentHi = "हज़रत सुलेमान (अलैहिस्सलाम) हज़रत दाऊद के बेटे थे। कम उम्र में ही उनकी बुद्धिमत्ता सबको हैरान कर देती थी। अल्लाह ने उन्हें ऐसा साम्राज्य दिया जैसा न उनसे पहले किसी को मिला न बाद में: वह जानवरों और पक्षियों की भाषा समझते थे, हवा उनके आदेश का पालन करती थी, और जिन्न भी उनके सेवा में काम करते थे।\n\nएक दिन वह अपनी बहुत बड़ी सेना के साथ जा रहे थे कि ज़मीन पर एक छोटी-सी चींटी की आवाज़ सुनी। वह अपनी साथियों को पुकार रही थी: 'ऐ चींटियो! अपने बिलों में घुस जाओ, कहीं सुलेमान और उनकी सेना तुम्हें अनजाने में कुचल न डाले।' सुलेमान उसकी बात सुनकर मुस्कुरा दिए और दुआ की: 'ऐ मेरे रब! मुझे तौफ़ीक दे कि मैं तेरी और मेरे माता-पिता पर की गई नेमतों का शुक्र अदा करूँ और ऐसे नेक काम करूँ जो तुझे पसंद हों।'\n\nबाद में सुलेमान ने अपने पक्षियों का जायज़ा लिया तो संदेशवाहक हुदहुद (पक्षियों का एक प्रकार) को गायब पाया। जब हुदहुद लौटा तो एक खबर लेकर आया: वह सबा देश तक गया था, जहाँ एक रानी शासन करती है और वह और उसकी कौम सूरज की पूजा करते हैं। सुलेमान ने एक पत्र भेजा और उन्हें सूरज की पूजा छोड़कर अल्लाह पर ईमान लाने का निमंत्रण दिया।\n\nजब रानी सबा मिलने के लिए आने लगी तो सुलेमान ने दरबारियों से पूछा कि रानी के आने से पहले उसका सिंहासन कौन ला सकता है? एक जिन्न ने कहा: 'मैं आपके अपनी जगह से उठने से पहले ला दूँगा।' मगर एक व्यक्ति जिसके पास अल्लाह की किताब का ज्ञान था, कहने लगा: 'मैं पलक झपकने से पहले ले आऊँगा।' और सचमुच सिंहासन एक ही पल में मौजूद हो गया।\n\nरानी सिंहासन, शीशे के फ़र्श (जिसे उसने पानी समझा) और सुलेमान की अल्लाह के सामने विनम्रता देखकर हैरान रह गई। उसने इस्लाम स्वीकार कर लिया और कहा: 'ऐ मेरे रब! मैंने अपनी जान पर ज़ुल्म किया, अब मैं सुलेमान के साथ सभी जहानों के रब अल्लाह पर ईमान लाती हूँ।'"
        ),
        Story(
            id = "ayyub",
            emoji = "💗",
            titleEn = "Prophet Ayyub",
            titleUr = "حضرت ایوب علیہ السلام",
            titleAr = "نبي الله أيوب عليه السلام",
            titleHi = "पैगंबर अय्यूब (अलैहिस्सलाम)",
            taglineEn = "The Patient One",
            taglineUr = "صبر کا پیکر",
            taglineAr = "رمز الصبر والثبات",
            taglineHi = "सब्र और धैर्य की मिसाल",
            lessonEn = "Patience through hardship brings Allah's mercy and reward.",
            lessonUr = "مشکل میں صبر اللہ کی رحمت اور انعام لاتا ہے۔",
            lessonAr = "الصبر عند البلاء يفتح أبواب الرحمة والفرج والتعويض العظيم.",
            lessonHi = "कठिनाई में सब्र करना अल्लाह की रहमत और बड़ा इनाम लाता है।",
            contentEn = "Prophet Ayyub (Job) was a man Allah had blessed with everything: a loving wife, many children, vast lands, healthy animals, and strong health. He was famous for his kindness, his constant charity, and never missing his worship of Allah. He thanked Allah for every single blessing, day and night.\n\nTo show his true rank, Allah tested Ayyub. First his wealth was lost. Then a great disaster took his children. Then his strong body became filled with sickness, and the illness lasted for many, many years. One by one, even his friends and relatives turned away from him. Only his faithful wife stayed by his side, working hard to bring him food and care.\n\nBut through all of this, Ayyub never once complained. He kept his tongue busy with the praise of Allah. He kept saying 'Alhamdulillah' even when his body shook with pain. He used to say, 'Allah gave me good for many years — should I not be patient now?'\n\nAt last, when the suffering became almost unbearable, Ayyub turned to Allah with the gentlest, most respectful prayer: 'Indeed, harm has touched me, and You are the Most Merciful of the merciful.' He did not demand. He did not complain. He simply mentioned his state to Allah.\n\nAllah answered immediately. He told Ayyub to strike the ground with his foot. Where his foot touched, a cool, fresh spring of water burst out. Ayyub drank from it and washed his body — and his pain disappeared! Allah healed him completely, returned his family, multiplied his wealth, and made him an everlasting symbol of sabr (patience) for all time.",
            contentUr = "حضرت ایوب علیہ السلام پر اللہ کی بے شمار نعمتیں تھیں: محبت کرنے والی بیوی، ڈھیر سارے بچے، وسیع زمینیں، صحت مند جانور اور مضبوط جسم۔ آپ اپنی نرمی، صدقہ خیرات اور ہمیشہ کی عبادت کی وجہ سے مشہور تھے۔ دن رات ہر نعمت پر اللہ کا شکر ادا کرتے۔\n\nان کے اصلی مقام کو ظاہر کرنے کے لیے اللہ نے انہیں آزمایا۔ پہلے ساری دولت چلی گئی۔ پھر ایک بڑے حادثے میں اولاد جاتی رہی۔ پھر مضبوط جسم بیماری سے بھر گیا اور یہ تکلیف کئی سال جاری رہی۔ آہستہ آہستہ دوست اور رشتہ دار بھی منہ موڑ گئے۔ صرف ان کی وفادار بیوی ساتھ رہی، محنت کر کے کھانا لاتی اور خدمت کرتی۔\n\nمگر ان سب آزمائشوں میں ایوبؑ نے کبھی ایک حرفِ شکوہ زبان پر نہیں لایا۔ ان کی زبان ہمیشہ اللہ کی حمد سے تر رہی۔ جب درد سے بدن کانپتا تب بھی 'الحمد للہ' ہی کہتے۔ فرمایا کرتے: 'اللہ نے کئی برس مجھے بھلائی دی، اب صبر کیوں نہ کروں؟'\n\nآخر جب تکلیف ناقابلِ برداشت ہونے لگی تو ایوب نے بڑے ادب اور نرمی سے اللہ کو پکارا: 'بے شک مجھے تکلیف پہنچی ہے، اور تو سب سے زیادہ رحم کرنے والا ہے۔' نہ کوئی شکایت، نہ کوئی مطالبہ، صرف اپنی حالت اللہ کے سامنے بیان کر دی۔\n\nاللہ نے فوراً جواب دیا۔ حکم ہوا کہ زمین پر اپنا پاؤں ماریں۔ جہاں پاؤں لگا، وہاں ٹھنڈے میٹھے پانی کا چشمہ پھوٹ پڑا۔ ایوب نے اس سے پیا اور غسل کیا — اور تمام تکلیف رفع ہو گئی! اللہ نے انہیں مکمل شفا دی، اہل و عیال واپس لوٹائے، مال میں اضافہ کیا اور ایوبؑ کو ہمیشہ کے لیے صبر کی علامت بنا دیا۔",
            contentAr = "أنعم الله على أيوب عليه السلام بنعم كثيرة: المال والأراضي الخصبة والذرية الصالحة والصحة والقوة. وكان عبداً شكوراً جواداً يعطف على المساكين ولا يفتر عن ذكر ربه.\n\nابتلى الله أيوب في ماله وولده وجسده، ففقد ثروته ومات أبناؤه، وأصابه مرض شديد مكث فيه سنوات طويلة حتى نفض عنه الناس إلا زوجته الوفية التي صبرت وعملت لخدمته ورعايته.\n\nورغم كل هذا البلاء الشديد، لم يتذمر أيوب قط ولم يسخط، بل ظل ثابتاً صابراً يحمد الله ليلاً ونهاراً. فلما اشتد به المرض دعا ربه بأدب الضعفاء: 'أَنِّي مَسَّنِيَ الضُّرُّ وَأَنْتَ أَرْحَمُ الرَّاحِمِينَ'.\n\nاستجاب الله دعاءه وأمره أن يضرب الأرض برجله، فانفجرت عين ماء باردة، فشرب واغتسل منها فبرئ من كل داء وعادت إليه صحته وشبابه. وعوضه الله عن ماله وأهله وأضعافهم معه رحمة من عنده وذكراه العطرة للصابرين.",
            contentHi = "हज़रत अय्यूब (अलैहिस्सलाम) पर अल्लाह की अनगिनत नेमतें थीं: प्यार करने वाली पत्नी, बहुत सारे बच्चे, विशाल ज़मीनें, स्वस्थ जानवर और मज़बूत सेहत। वह अपनी दयालुता, दान-पुण्य और निरंतर इबादत के लिए प्रसिद्ध थे। दिन-रात हर नेमत के लिए अल्लाह का शुक्र अदा करते थे।\n\nउनके सच्चे दर्जे को दिखाने के लिए अल्लाह ने उनकी परीक्षा ली। पहले सारी दौलत चली गई। फिर एक बड़ी दुर्घटना में बच्चे नहीं रहे। फिर मज़बूत शरीर बीमारी से घिर गया और यह बीमारी कई वर्षों तक चली। धीरे-धीरे दोस्त और रिश्तेदार भी मुँह मोड़ गए। सिर्फ़ उनकी वफ़ादार पत्नी साथ रहीं, मेहनत करके खाना लातीं और सेवा करतीं।\n\nलेकिन इन सभी परीक्षाओं में अय्यूब (अलैहिस्सलाम) ने कभी एक शब्द भी शिकायत का नहीं कहा। उनकी ज़बान हमेशा अल्लाह की प्रशंसा (हमद) में व्यस्त रही। जब दर्द से शरीर काँपता तब भी 'अलहम्दुलिल्लाह' ही कहते। वह कहा करते थे: 'अल्लाह ने कई साल मुझे सुख दिया, अब क्या मैं सब्र न करूँ?'\n\nआखिरकार जब दर्द असहनीय होने लगा तो अय्यूब ने बड़े अदब और विनम्रता से अल्लाह से प्रार्थना की: 'बेशक मुझे तकलीफ़ पहुँची है, और तू सबसे ज़्यादा रहम करने वाला है।' कोई शिकायत नहीं, कोई माँग नहीं, बस अपनी स्थिति अल्लाह के सामने रख दी।\n\nअल्लाह ने तुरंत जवाब दिया। आदेश हुआ कि ज़मीन पर अपना पैर मारें। जहाँ पैर लगा, वहाँ ठंडे और मीठे पानी का एक झरना फूट पड़ा। अय्यूब ने उससे पानी पिया और स्नान किया — और सारा दर्द गायब हो गया! अल्लाह ने उन्हें पूर्ण स्वास्थ्य दिया, परिवार लौटाया, धन में वृद्धि की और अय्यूब को हमेशा के लिए सब्र (धैर्य) का प्रतीक बना दिया।"
        ),
        Story(
            id = "isa",
            emoji = "👶",
            titleEn = "Prophet Isa",
            titleUr = "حضرت عیسیٰ علیہ السلام",
            titleAr = "نبي الله عيسى عليه السلام",
            titleHi = "पैगंबर ईसा (अलैहिस्सलाम)",
            taglineEn = "The Miracle Baby",
            taglineUr = "معجزاتی بچہ",
            taglineAr = "معجزة الولادة وآيات الخالق",
            taglineHi = "चमत्कारी बालक",
            lessonEn = "Allah can do anything — nothing is too hard for Him.",
            lessonUr = "اللہ ہر چیز پر قادر ہے — کوئی بات اس کے لیے مشکل نہیں۔",
            lessonAr = "قدرة الله مطلقَة، يخلُق ما يشاء بكلمة كُن فيكون.",
            lessonHi = "अल्लाह हर चीज़ पर सक्षम है — उसके लिए कोई काम मुश्किल नहीं।",
            contentEn = "Maryam (Mary) was a pure and pious young woman who grew up worshipping Allah inside the temple. She fasted, prayed, and lived a quiet life of devotion. People who met her felt the noor (light) of her good character.\n\nOne day, the angel Jibreel came to Maryam in the form of a man. She was scared and said, 'I seek refuge in the Most Merciful from you, if you are God-fearing.' Jibreel calmed her and said, 'I am only a messenger from your Lord, to give you a pure son.' Maryam asked, 'How can I have a son when no man has touched me?' Jibreel said, 'It is easy for your Lord. He has decreed it.'\n\nBy the will of Allah, Maryam became pregnant. When her time came, she went away to a quiet place near a date palm. The birth was painful and she felt afraid of what people would say. Allah comforted her: a stream of water flowed near her feet, and fresh dates fell from the palm tree.\n\nWhen she returned to her people carrying the baby, they were shocked. They gossiped and accused her. Maryam simply pointed to the baby. The people scoffed, 'How can we speak to a baby in the cradle?' But then the newborn Isa (Jesus) spoke clearly from the cradle: 'I am a servant of Allah. He has given me the Book and made me a prophet. He has blessed me wherever I am, and commanded me to pray and give zakah as long as I live.'\n\nWhen Isa grew up, Allah gave him many miracles, all by Allah's permission: he healed people born blind, cured leprosy, breathed life into a clay bird, and even raised the dead. He called people to worship Allah alone — not himself, not statues, not anything else. When his enemies plotted to kill him, Allah raised him alive up to the heavens, and one day he will return.",
            contentUr = "حضرت مریمؑ ایک پاک دامن اور پرہیزگار جوان لڑکی تھیں جو بیت المقدس میں ہی اللہ کی عبادت کرتی رہیں۔ وہ روزے رکھتیں، نمازیں پڑھتیں اور خاموشی سے عبادت میں مصروف رہتیں۔ جو ان سے ملتا، ان کے اخلاق کا نور محسوس کرتا۔\n\nایک دن فرشتہ جبرئیلؑ ایک انسان کی شکل میں مریم کے پاس آیا۔ وہ گھبرا گئیں اور بولیں: 'میں تجھ سے رحمن کی پناہ مانگتی ہوں اگر تو پرہیزگار ہے۔' جبرئیل نے انہیں تسلی دی: 'میں صرف تیرے رب کا بھیجا ہوا ہوں، تجھے ایک پاک بیٹا دینے آیا ہوں۔' مریم نے پوچھا: 'میرے بیٹا کیسے ہو سکتا ہے جبکہ کسی مرد نے مجھے چھوا تک نہیں؟' جبرئیل نے کہا: 'تیرے رب کے لیے یہ آسان ہے، اس نے یہ مقدر کر دیا ہے۔'\n\nاللہ کی مرضی سے مریم حاملہ ہو گئیں۔ جب وقت آیا تو وہ ایک تنہا جگہ، ایک کھجور کے پیڑ کے پاس چلی گئیں۔ زچگی کی تکلیف اور لوگوں کے طعنوں کا خوف ان پر طاری ہو گیا۔ اللہ نے ان کو تسلی دی: ان کے پاؤں کے قریب پانی کا چشمہ بہنے لگا اور درخت سے تازہ کھجوریں گرنے لگیں۔\n\nجب وہ بچے کو لے کر اپنی قوم کے پاس واپس آئیں تو سب سکتے میں آ گئے۔ لوگوں نے باتیں بنانی شروع کر دیں۔ مریم نے بس بچے کی طرف اشارہ کیا۔ لوگ ہنسے: 'بھلا گود کے بچے سے کیسے بات کریں؟' اسی وقت نوزائیدہ عیسیٰؑ نے گود میں سے صاف الفاظ میں فرمایا: 'میں اللہ کا بندہ ہوں۔ اس نے مجھے کتاب دی اور نبی بنایا۔ مجھے جہاں بھی ہوں بابرکت بنایا اور جب تک زندہ رہوں نماز اور زکوٰۃ کا حکم دیا۔'\n\nجب عیسیٰ بڑے ہوئے تو اللہ نے انہیں بہت سے معجزے عطا کیے، اور ہر معجزہ اللہ ہی کے حکم سے: پیدائشی اندھوں کو شفا دی، کوڑھ کا علاج کیا، مٹی سے پرندہ بنا کر اس میں جان ڈالی اور یہاں تک کہ مردوں کو زندہ کیا۔ آپ نے لوگوں کو صرف اللہ کی عبادت کی دعوت دی — نہ خود کی، نہ بتوں کی، نہ کسی اور کی۔ جب دشمنوں نے قتل کی سازش کی تو اللہ نے انہیں زندہ ہی آسمان پر اٹھا لیا، اور ایک دن وہ دوبارہ تشریف لائیں گے۔",
            contentAr = "نشأت مريم العذراء الصديقة في المحراب تتعبد لله بطهارة وتقوى. وفي أحد الأيام تمثل لها الملك جبريل في صورة بشر، فخافت واستعاذت بالله منه، فطمأنها وأخبرها أنه رسول ربها ليبشرها بغلام زكي.\n\nتعجبت مريم وقالت: 'أَنَّى يَكُونُ لِي غُلَامٌ وَلَمْ يَمْسَسْنِي بَشَرٌ وَلَمْ أَكُ بَغِيّاً'. فأجابها الملك أن هذا أمر يسير على قدرة الله الذي يخلق ما يشاء.\n\nحملت مريم بعيسى عليه السلام ولجأت عند المخاض إلى جذع نخلة في مكان قصي. رزقها الله جدول ماء عذب تحتها وأمرها وهز جذع النخلة لتساقط عليها رطباً جنياً.\n\nلما عادت مريم بطفلها إلى قومها أساؤوا الظن بها، فأشارت إلى الرضيع في المهد. فنطق عيسى بطلاقة معجزاً: 'إِنِّي عَبْدُ اللَّهِ آتَانِيَ الْكِتَابَ وَجَعَلَنِي نَبِيّاً وَجَعَلَنِي مُبَارَكاً أَيْنَ مَا كُنْتُ وَأَوْصَانِي بِالصَّلَاةِ وَالزَّكَاةِ مَا دُمْتُ حَيّاً'.\n\nأيد الله عيسى بمعجزات باهرة بإذنه: يبرئ الأكمه والأبرص ويحيي الموتى ويصنع من الطين كهيئة الطير فينفخ فيه فيكون طيراً بإذن الله. دعا إلى توحيد الله وحده. ولما دبر أعداؤه لقتله، رفعه الله إليه وسيعود في آخر الزمان.",
            contentHi = "हज़रत मरियम एक पवित्र और परहेज़गार युवती थीं, जो बैतुल-मुकद्दस (मंदिर) में ही अल्लाह की इबादत करती थीं। वह रोज़े रखतीं, नमाज़ पढ़तीं और शांति से भक्ति में लीन रहतीं। जो भी उनसे मिलता, उनके सदाचार का प्रकाश महसूस करता।\n\nएक दिन फ़रिश्ता जिब्रील एक इंसान के रूप में मरियम के पास आए। वह डर गईं और बोलीं: 'मैं तुमसे दयालु रब की पनाह माँगती हूँ अगर तुम अल्लाह से डरने वाले हो।' जिब्रील ने उन्हें तसल्ली दी: 'मैं सिर्फ़ तुम्हारे रब का भेजा हुआ दूत हूँ, तुम्हें एक पवित्र पुत्र देने आया हूँ।' मरियम ने पूछा: 'मेरे पुत्र कैसे हो सकता है जबकि किसी पुरुष ने मुझे छुआ तक नहीं?' जिब्रील ने कहा: 'तुम्हारे रब के लिए यह आसान है, उसने यह तय कर दिया है।'\n\nअल्लाह की इच्छा से मरियम गर्भवती हुईं। जब समय आया तो वह एक एकांत स्थान पर, एक खजूर के पेड़ के पास चली गईं। प्रसव की पीड़ा और लोगों के तानों का डर उन पर छा गया। अल्लाह ने उन्हें सांत्वना दी: उनके पैरों के पास पानी का एक झरना बहने लगा और पेड़ से ताज़ी खजूरें गिरने लगीं।\n\nजब वह बच्चे को लेकर अपनी कौम के पास वापस आईं तो सब हैरान रह गए। लोगों ने बातें बनानी शुरू कर दीं। मरियम ने बस बच्चे की तरफ इशारा किया। लोग हँसे: 'भला गोद के बच्चे से कैसे बात करें?' उसी समय नवजात ईसा (अलैहिस्सलाम) ने गोद में से साफ़ शब्दों में कहा: 'मैं अल्लाह का बंदा हूँ। उसने मुझे किताब दी है और पैगंबर बनाया है। मुझे जहाँ भी रहूँ बरकत वाला बनाया है और जब तक जीवित रहूँ नमाज़ और ज़कात का आदेश दिया है।'\n\nजब ईसा बड़े हुए तो अल्लाह ने उन्हें कई चमत्कार दिए, और हर चमत्कार अल्लाह की आज्ञा से: जन्मजात अंधों को ठीक किया, कुष्ठ रोग (कोढ़) का इलाज किया, मिट्टी से पक्षी बनाकर उसमें जान डाली और यहाँ तक कि मुर्दों को जीवित किया। उन्होंने लोगों को सिर्फ़ अल्लाह की इबादत करने का निमंत्रण दिया। जब दुश्मनों ने उन्हें मारने की साजिश रची तो अल्लाह ने उन्हें जीवित ही आसमान पर उठा लिया, और एक दिन वह फिर वापस आएँगे।"
        ),
        Story(
            id = "muhammad",
            emoji = "☪️",
            titleEn = "Prophet Muhammad ﷺ",
            titleUr = "حضرت محمد ﷺ",
            titleAr = "نبينا محمد ﷺ",
            titleHi = "पैगंबर मुहम्मद ﷺ",
            taglineEn = "The Last Messenger",
            taglineUr = "آخری رسول",
            taglineAr = "خاتم الأنبياء والمرسلين ورحمة للعالمين",
            taglineHi = "अंतिम संदेशवाहक और सारे जहान के लिए रहमत",
            lessonEn = "Be honest, kind, and a mercy to everyone around you.",
            lessonUr = "سچے بنو، نرم دل رکھو اور سب کے لیے رحمت بنو۔",
            lessonAr = "كن صادقاً أميناً، ورحيماً بكل من حولك كما كان رسول الله ﷺ.",
            lessonHi = "सच्चे बनो, दयालु रहो और अपने आस-पास के सभी लोगों के लिए रहमत (दया) बनो।",
            contentEn = "Muhammad ﷺ was born in the holy city of Makkah in the Year of the Elephant. His father died before he was born, and his mother passed away when he was only six. He was then raised by his loving grandfather Abdul-Muttalib, and after that by his kind uncle Abu Talib.\n\nFrom childhood, Muhammad ﷺ was different from everyone around him. He never lied, never broke a promise, and never harmed anyone. The people of Makkah trusted him so much that they called him 'Al-Amin' — The Trustworthy. He helped the poor, cared for orphans, and stood up for the weak. He even rebuilt the Kaaba peacefully when the tribes were about to fight over which one would place the holy Black Stone — he laid it on his cloak and let every tribe carry an edge together.\n\nAt the age of forty, while praying alone in the cave of Hira on the mountain of Nur, the angel Jibreel came to him for the first time. Jibreel hugged him tightly and said, 'Read!' Muhammad ﷺ replied, 'I cannot read.' Jibreel hugged him again and said, 'Read in the name of your Lord who created — created man from a clinging clot. Read, and your Lord is the Most Generous, who taught by the pen — taught man what he did not know.' These were the very first words of the Holy Quran.\n\nFor the next twenty-three years, the Quran was revealed to him bit by bit. He taught people to worship only Allah, to be kind to neighbors, to honor parents, to set slaves free, to treat women with respect, to care for orphans, and to be gentle to animals. The people of Makkah were cruel to him and his followers. They mocked him, hit him, starved him, and forced him to leave his beloved city.\n\nHe went to Madinah, built the first mosque, and slowly the message of Islam spread far and wide. When he finally returned to Makkah as a victor, he forgave even those who had hurt him the most. Allah called him 'a mercy to all the worlds' — and his beautiful life remains the best example for every Muslim until the Day of Judgment.",
            contentUr = "حضرت محمد ﷺ مقدس شہر مکہ میں عام الفیل میں پیدا ہوئے۔ ان کے والد ان کی پیدائش سے پہلے ہی انتقال کر گئے تھے اور والدہ صرف چھ سال کی عمر میں رخصت ہوگئیں۔ اس کے بعد ان کی پرورش پیارے دادا عبد المطلب نے کی اور پھر مہربان چچا ابو طالب نے۔\n\nبچپن ہی سے حضرت محمد ﷺ سب سے مختلف تھے۔ آپ نے کبھی جھوٹ نہ بولا، کبھی وعدہ نہ توڑا، کسی کو کبھی تکلیف نہ دی۔ اہلِ مکہ آپ پر اتنا بھروسہ کرتے تھے کہ آپ کو 'الامین' (یعنی امانت دار) کہتے تھے۔ آپ غریبوں کی مدد کرتے، یتیموں کا خیال رکھتے اور کمزوروں کے حق کے لیے کھڑے ہوتے۔ جب قبیلے کعبہ میں حجرِ اسود رکھنے پر لڑنے کو تیار ہو گئے تو آپ نے امن کا حل پیش کیا: پتھر ایک چادر پر رکھ کر ہر قبیلے کے سردار کو اس کا ایک کونا اٹھانے دیا۔\n\nچالیس برس کی عمر میں جب آپ غارِ حرا میں عبادت میں مشغول تھے، فرشتہ جبرئیلؑ پہلی بار حاضر ہوا۔ آپ کو زور سے بھینچا اور کہا: 'پڑھیے!' آپ ﷺ نے فرمایا: 'میں پڑھا ہوا نہیں ہوں۔' جبرئیل نے دوبارہ بھینچا اور کہا: 'پڑھیے اپنے رب کے نام سے جس نے پیدا کیا — انسان کو خون کے لوتھڑے سے پیدا کیا۔ پڑھیے اور آپ کا رب بہت کریم ہے، جس نے قلم سے سکھایا، انسان کو وہ سکھایا جو وہ نہیں جانتا تھا۔' یہ قرآن مجید کی پہلی آیات تھیں۔\n\nاس کے بعد تئیس سال میں قرآن آہستہ آہستہ نازل ہوتا رہا۔ آپ نے لوگوں کو سکھایا کہ صرف اللہ کی عبادت کرو، پڑوسیوں سے نیکی کرو، والدین کا ادب کرو، غلام آزاد کرو، عورتوں کا احترام کرو، یتیموں کا خیال رکھو اور جانوروں سے بھی نرمی برتو۔ مکہ والوں نے آپ اور آپ کے ساتھیوں پر بہت ظلم کیے، مذاق اڑایا، مارا، بھوکا رکھا اور آخر آپ کو پیارا شہر چھوڑنے پر مجبور کیا۔\n\nآپ مدینہ تشریف لائے، پہلی مسجد بنائی، اور اسلام دور دور تک پھیلتا چلا گیا۔ جب آپ مکہ فاتح بن کر واپس داخل ہوئے تو ان لوگوں کو بھی معاف کر دیا جنہوں نے سب سے زیادہ تکلیف دی تھی۔ اللہ نے آپ کو 'تمام جہانوں کے لیے رحمت' فرمایا — اور آپ کی خوبصورت زندگی قیامت تک ہر مسلمان کے لیے بہترین نمونہ ہے۔",
            contentAr = "ولد النبي محمد ﷺ في مكة المكرمة في عام الفيل. توفي والده قبل ولادته وتوفيت والدته وهو في السادسة من عمره، فكفله جده عبد المطلب ثم عمه أبو طالب.\n\nتمتع محمد ﷺ بالأخلاق العالية والصدق والأمانة منذ طفولته، حتى لقبه أهل مكة بـ 'الصادق الأمين'. كان ينصر الضعيف ويعين المحتاج، وقد حل خلاف القبائل بحكمة عند وضع الحجر الأسود ببسط ردائه ليحمله الجميع معاً دون قتال.\n\nفي سن الأربعين، وبينما كان يتعبد في غار حراء بجبل النور، نزل عليه الملك جبريل بالوحي قائلاً: 'اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ'. فكانت تلك أول آيات القرآن الكريم.\n\nاستمر نزول القرآن ثلاثاً وعشرين سنة، يدعو فيها إلى التوحيد ومكارم الأخلاق، والعدل، وبر اليدين، والرفق بالحيوان، وإكرام المرأة واليتيم. واجه أذى شديداً من قريش وهاجر إلى المدينة المنورة حيث أسس الدولة الإسلامية وبنى أول مسجد.\n\nولما عاد فاتحاً لمكة، عفا عن ألد أعدائه قائلاً: 'اذهبوا فأنتم الطلقاء'. وقد وصفه الله تعالى بقوله: 'وَمَا أَرْسَلْنَاكَ إِلَّا رَحْمَةً لِلْعَالَمِينَ'.",
            contentHi = "हज़रत मुहम्मद ﷺ मक्का के पवित्र शहर में आमुल-फ़ील (हाथियों वाले वर्ष) में पैदा हुए। उनके पिता का निधन उनकी पैदाइश से पहले ही हो गया था और जब वह सिर्फ़ छह साल के थे तो माता का भी साया उठ गया। इसके बाद उनके प्यारे दादा अब्दुल-मुत्तलिब और फिर मेहरबान चाचा अबू तालिब ने उनका पालन-पोषण किया।\n\nबचपन से ही हज़रत मुहम्मद ﷺ सबसे अलग थे। उन्होंने कभी झूठ नहीं बोला, कभी वादा नहीं तोड़ा और किसी को कभी नुकसान नहीं पहुँचाया। मक्का के लोग उन पर इतना भरोसा करते थे कि उन्हें 'अल-अमीन' (यानी अमानतदार / भरोसेमंद) कहते थे। वह गरीबों की मदद करते, अनाथों का ख्याल रखते और कमज़ोरों के हक़ के लिए खड़े होते। जब कबीले काबा में हज़रे-असवद (पवित्र काला पत्थर) रखने पर लड़ने को तैयार हो गए तो उन्होंने शांति का हल निकाला: पत्थर एक चादर पर रखकर हर कबीले के सरदार को उसका एक कोना उठाने दिया।\n\nचालीस वर्ष की उम्र में जब वह गारे-हिरा (हिरा गुफ़ा) में इबादत में व्यस्त थे, तो फ़रिश्ता जिब्रील पहली बार आए। जिब्रील ने उन्हें ज़ोर से गले लगाया और कहा: 'पढ़िए!' आप ﷺ ने फरमाया: 'मैं पढ़ा हुआ नहीं हूँ।' जिब्रील ने दोबारा गले लगाया और कहा: 'पढ़िए अपने रब के नाम से जिसने पैदा किया — इंसान को खून के लोथड़े से पैदा किया। पढ़िए और आपका रब बहुत कृपालु है, जिसने कलम से सिखाया, इंसान को वह सिखाया जो वह नहीं जानता था।' ये पवित्र कुरआन की पहली आयतें थीं।\n\nइसके बाद तेईस साल तक कुरआन धीरे-धीरे नाज़िल (अवतरित) होता रहा। आपने लोगों को सिखाया कि सिर्फ़ अल्लाह की इबादत करो, पड़ोसियों से भलाई करो, माता-पिता का आदर करो, गुलामों को आज़ाद करो, महिलाओं का सम्मान करो, अनाथों का ख्याल रखो और जानवरों के साथ भी नरमी बरतो। मक्का वालों ने आप और आपके साथियों पर बहुत ज़ुल्म किए, मज़ाक उड़ाया, मारा, भूखा रखा और अंत में आपको प्यारा शहर छोड़ने पर मजबूर किया।\n\nआप मदीना تشریف (तशरीफ़) लाए, पहली मस्जिद बनाई, और इस्लाम दूर-दूर तक फैलता चला गया। जब आप मक्का विजेता बनकर वापस आए तो उन लोगों को भी माफ़ कर दिया जिन्होंने सबसे ज़्यादा तकलीफ़ दी थी। अल्लाह ने आपको 'सारे जहानों के लिए रहमत' फरमाया — और आपका सुंदर जीवन कयामत तक हर मुसलमान के लिए सर्वोत्तम आदर्श है।"
        ),
        Story(
            id = "cave",
            emoji = "😴",
            titleEn = "Companions of the Cave",
            titleUr = "اصحابِ کہف",
            titleAr = "أصحاب الكهف",
            titleHi = "अस्हाब-ए-कहफ़ (गुफ़ा के साथी)",
            taglineEn = "The Sleepers of Faith",
            taglineUr = "ایمان والے سونے والے",
            taglineAr = "الفتية المؤمنون وآية البعث",
            taglineHi = "ईमान वाले युवा और गुफ़ा का चमत्कार",
            lessonEn = "Allah protects believers in ways we cannot imagine.",
            lessonUr = "اللہ ایمان والوں کو ایسی صورتوں میں بچاتا ہے جو ہم سوچ بھی نہیں سکتے۔",
            lessonAr = "الله يحفظ المؤمنين المعتصمين به من حيث لا يحتسبون.",
            lessonHi = "अल्लाह ईमान वालों को ऐसे तरीकों से बचाता है जिसकी हम कल्पना भी नहीं कर सकते।",
            contentEn = "Long, long ago, in a faraway city, there lived a group of brave young men. Their city was ruled by a cruel king who forced everyone to worship idols. Anyone who refused was punished severely.\n\nThese young men were different. They had thought deeply about the sun, the moon, and the wide sky, and they realized that none of these were gods — they were all created. There must be only one Creator. So in their hearts they secretly believed in Allah.\n\nOne day, they could not hide their faith any longer. They met together, stood firm, and said publicly, 'Our Lord is the Lord of the heavens and the earth. We will never call upon any god besides Him.' The king heard about them and ordered them caught.\n\nThe young men quickly fled the city, with their loyal dog following behind. They climbed up to a quiet, hidden cave in the mountains. There they raised their hands and prayed, 'Our Lord, give us mercy from Yourself and guide us in our matter to what is right.'\n\nAllah accepted their prayer in an amazing way: He caused them to fall into a deep, peaceful sleep — for more than three hundred years! While they slept, Allah turned them from side to side so their bodies stayed healthy, and their dog lay watching at the entrance.\n\nWhen they finally woke up, they felt like they had slept only a day or part of a day. They sent one of them down with an old silver coin to buy food in the city. But when he reached the city, everything was different. The buildings, the clothes, the language had changed. When he tried to pay, the shopkeeper stared at the coin — it was hundreds of years old!\n\nThe whole city soon learned what had happened. The people had long since believed in Allah, and now they had this incredible sign right in front of them. Allah tells this story in Surah Al-Kahf to remind every Muslim: never fear standing up for your faith. Allah always protects those who trust Him.",
            contentUr = "بہت پرانے زمانے کی بات ہے، ایک دور دراز شہر میں چند بہادر نوجوان رہتے تھے۔ ان کے شہر پر ایک ظالم بادشاہ کی حکومت تھی جو سب کو بتوں کی پوجا پر مجبور کرتا اور انکار کرنے والوں کو سخت سزا دیتا۔\n\nمگر یہ نوجوان سب سے الگ تھے۔ انہوں نے سورج، چاند اور وسیع آسمان پر غور کیا اور سمجھ گئے کہ یہ سب خدا نہیں — یہ سب پیدا کیے گئے ہیں۔ ایک ہی خالق ہے۔ چنانچہ ان کے دلوں میں چپکے سے اللہ پر ایمان جاگزیں ہو گیا۔\n\nایک دن وہ اپنا ایمان مزید چھپا نہ سکے۔ سب اکٹھے ہوئے، مضبوطی سے کھڑے ہوئے اور سب کے سامنے کہہ دیا: 'ہمارا رب آسمانوں اور زمین کا رب ہے، ہم اس کے سوا کسی کو معبود نہ پکاریں گے۔' بادشاہ کو خبر ملی تو اس نے انہیں پکڑنے کا حکم دے دیا۔\n\nنوجوان فوراً شہر سے نکلے، ان کا وفادار کتا بھی پیچھے ہو لیا۔ پہاڑوں میں ایک پُر سکون، چھپا ہوا غار تھا، وہیں چلے گئے۔ وہاں ہاتھ اٹھا کر دعا کی: 'اے ہمارے رب! اپنی طرف سے ہم پر رحمت نازل فرما اور ہمارے کام کو سیدھی راہ پر لگا دے۔'\n\nاللہ نے ان کی دعا ایک عجیب انداز میں قبول فرمائی: انہیں گہری، پُرسکون نیند سلا دیا — تین سو سال سے بھی زیادہ! نیند میں اللہ انہیں دائیں بائیں کروٹ بدلتا رہا تاکہ جسم صحیح سلامت رہیں، اور کتا غار کے دروازے پر بیٹھا پہرہ دیتا رہا۔\n\nجب وہ بیدار ہوئے تو انہیں لگا کہ بس ایک دن یا اس کا کچھ حصہ سو کر اٹھے ہیں۔ انہوں نے اپنے میں سے ایک کو پرانے سکّے کے ساتھ کھانے کا سامان لینے بھیجا۔ شہر پہنچا تو ہر چیز بدل چکی تھی۔ عمارتیں، کپڑے، زبان — سب۔ جب اس نے سکّہ آگے بڑھایا تو دکاندار حیران رہ گیا، کیونکہ وہ سکّہ سینکڑوں سال پرانا تھا!\n\nپورا شہر جلد ہی سب کچھ جان گیا۔ لوگ کب کے اللہ پر ایمان لا چکے تھے، اور اب یہ نشانی ان کی آنکھوں کے سامنے تھی۔ اللہ سورۃ الکہف میں یہ قصہ بیان کر کے ہر مسلمان کو یاد دلاتا ہے: ایمان پر قائم رہنے سے کبھی نہ ڈرنا، اللہ بھروسہ کرنے والوں کو ضرور بچاتا ہے۔",
            contentAr = "في زمن قديم، عاش فتية مؤمنون في مدينة يحكمها ملك جبار يجبر الناس على عبادة الأصنام ويضطهد الموحدين.\n\nأدرك هؤلاء الفتية بعقولهم الصافية أن الكون له إله واحد هو رب السماوات والأرض، فآمنوا به سراً. ولما افتضح أمرهم أمام الملك، رفضوا التنازل عن إيمانهم وفروا بدينهم ومعهم كلبهم الوفي إلى كهف في الجبل.\n\nدعا الفتية ربهُم قائلين: 'رَبَّنَا آتِنَا مِنْ لَدُنْكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَداً'. فاستجاب الله لهم وألقى عليهم نَوْماً عميقاً استمر ثلاثمائة وتسع سنوات. وكان الله يقلبهم ذات اليمين وذات الشمال لحفظ أجسادهم، وكلبهم باسط ذراعيه بالوصيد.\n\nلما استيقظوا ظنوا أنهم لبثوا يوماً أو بعض يوم، فأرسلوا أحدهم بنقودهم القديمة ليشتري طعاما. تعجب أهل المدينة حين رأوا العملة التي تعود لمئات السنين، واكتشفوا المعجزة. كان أهل المدينة حينها قد آمنوا بالله، فكان ظهور أصحاب الكهف آية قاطعة على قدرة الله على البعث.",
            contentHi = "बहुत पुराने समय की बात है, एक दूर शहर में कुछ बहादुर युवा रहते थे। उनके शहर पर एक क्रूर राजा का शासन था जो सभी को मूर्तियों की पूजा करने के लिए मजबूर करता था और इनकार करने वालों को कड़ी सज़ा देता था।\n\nलेकिन ये युवा सबसे अलग थे। उन्होंने सूरज, चाँद और विस्तृत आकाश पर गहराई से विचार किया और समझ गए कि ये सब ईश्वर नहीं हैं — ये सब बनाए गए हैं। एक ही बनाने वाला (रचयिता) है। इसलिए उनके दिलों में अल्लाह पर सच्चा ईमान बस गया।\n\nएक दिन वे अपना ईमान और नहीं छिपा सके। सब एक साथ आए, मजबूती से खड़े हुए और सबके सामने कह दिया: 'हमारा रब आसमानों और ज़मीन का रब है, हम उसके सिवा किसी को ईश्वर नहीं पुकारेंगे।' राजा को खबर मिली तो उसने उन्हें पकड़ने का आदेश दे दिया।\n\nयुवा तुरंत शहर से निकल गए, उनका वफ़ादार कुत्ता भी पीछे-पीछे चल दिया। पहाड़ों में एक शांत, छिपी हुई गुफ़ा थी, वहीं चले गए। वहाँ हाथ उठाकर दुआ की: 'ऐ हमारे रब! अपनी तरफ से हम पर रहमत नाज़िल फ़रमा और हमारे काम को सही रास्ते पर लगा दे।'\n\nअल्लाह ने उनकी दुआ एक अद्भुत तरीके से स्वीकार की: उन्हें गहरी, शांतिपूर्ण नींद सुला दिया — तीन सौ साल से भी ज़्यादा! नींद में अल्लाह उनकी करवटें बदलता रहा ताकि शरीर स्वस्थ रहें, और कुत्ता गुफ़ा के द्वार पर पहरा देता रहा।\n\nजब वे जागे तो उन्हें लगा कि बस एक दिन या उसका कुछ हिस्सा सोकर उठे हैं। उन्होंने अपने में से एक को पुराने चाँदी के सिक्के के साथ भोजन लेने के लिए शहर भेजा। शहर पहुँचा तो हर चीज़ बदल चुकी थी। इमारतें, कपड़े, भाषा — सब कुछ। जब उसने सिक्का आगे बढ़ाया तो दुकानदार हैरान रह गया, क्योंकि वह सिक्का सैकड़ों साल पुराना था!\n\nपूरा शहर जल्द ही सब कुछ जान गया। लोग पहले ही अल्लाह पर ईमान ला चुके थे, और अब यह निशानी उनकी आँखों के सामने थी। अल्लाह सूरह अल-कहफ़ में यह कहानी बयान करके हर मुसलमान को याद दिलाता है: अपने ईमान पर खड़े रहने से कभी मत डरो, अल्लाह भरोसा करने वालों को हमेशा बचाता है।"
        ),
        Story(
            id = "elephant",
            emoji = "🐘",
            titleEn = "The Elephant Army",
            titleUr = "ہاتھیوں کا لشکر",
            titleAr = "أصحاب الفيل",
            titleHi = "हाथियों की सेना (अस्हाब-ए-फ़ील)",
            taglineEn = "When Birds Defeated an Army",
            taglineUr = "جب پرندوں نے لشکر کو شکست دی",
            taglineAr = "طير أبابيل وحماية البيت العتيق",
            taglineHi = "जब पक्षियों ने एक विशाल सेना को हराया",
            lessonEn = "Allah protects His house — no power can stand against Him.",
            lessonUr = "اللہ اپنے گھر کی حفاظت کرتا ہے — کوئی طاقت اس کے سامنے نہیں ٹک سکتی۔",
            lessonAr = "للكعبة رب يحميها، وقدرة الله فوق كل قوة ومتجبر.",
            lessonHi = "अल्लाह अपने घर (काबा) की रक्षा करता है — कोई शक्ति उसके सामने नहीं टिक सकती।",
            contentEn = "In the very same year that the Prophet Muhammad ﷺ was born, something extraordinary happened in Makkah. A powerful king from Yemen named Abraha had built a huge, beautiful church and wanted everyone to come pray there instead of at the Kaaba. When the Arabs continued to honor the Kaaba, he became furious.\n\nAbraha gathered a massive army to march on Makkah and destroy the holy Kaaba forever. To make sure no one could stop him, he brought along giant elephants — including a famous huge elephant called Mahmoud. The earth trembled under their feet as they approached the city.\n\nThe people of Makkah were terrified. They were few in number and had no army that could stand against elephants. They quickly gathered their families and escaped to the mountains, watching from a distance. The Prophet's grandfather, Abdul-Muttalib, was the leader of the city. When Abraha demanded he hand over the Kaaba, Abdul-Muttalib calmly said, 'I am the owner of the camels, and the Kaaba has a Lord who will protect it.'\n\nAs the army got close to Makkah and prepared to attack, something amazing happened. The giant elephant Mahmoud stopped. No matter how much they hit him, beat him, or shouted at him, he refused to step forward toward the Kaaba. He simply knelt down on the ground.\n\nSuddenly, the sky grew dark. Allah sent thousands and thousands of small birds called Ababil from the direction of the sea. Each bird carried three tiny stones — one in its beak and two in its claws. They flew over the army and dropped the stones. Each tiny stone struck a soldier and destroyed him completely, leaving them like 'eaten straw,' as the Quran describes.\n\nAbraha himself fell sick and died on the way home. The huge army was wiped out. The Kaaba stood completely safe. Allah told this story in Surah Al-Fil to remind all of us: when Allah decides to protect something, no power in the world — not even an army with elephants — can harm it.",
            contentUr = "جس سال نبی کریم ﷺ پیدا ہوئے، اسی سال مکہ میں ایک بہت بڑا واقعہ پیش آیا۔ یمن کے ایک طاقتور بادشاہ ابرہہ نے ایک عظیم اور خوبصورت چرچ بنایا تھا اور چاہتا تھا کہ سب لوگ کعبہ کی بجائے وہاں آ کر عبادت کریں۔ جب عرب پھر بھی کعبہ کا احترام کرتے رہے تو ابرہہ غصے سے آپے سے باہر ہو گیا۔\n\nاس نے ایک بہت بڑا لشکر اکٹھا کیا تاکہ مکہ پر چڑھائی کر کے کعبہ کو ہمیشہ کے لیے گرا دے۔ اپنی طاقت دکھانے کے لیے وہ بڑے بڑے ہاتھی بھی ساتھ لایا، جن میں ایک مشہور بہت بڑا ہاتھی 'محمود' بھی تھا۔ لشکر کے قدموں سے زمین کانپتی تھی۔\n\nمکہ والے بہت گھبرا گئے۔ ان کی تعداد کم تھی اور ایسا کوئی لشکر نہ تھا جو ہاتھیوں کا مقابلہ کر سکے۔ انہوں نے اپنے گھر والوں کو لے کر پہاڑوں کا رخ کیا اور دور سے دیکھنے لگے۔ نبی کریم ﷺ کے دادا عبد المطلب اس وقت مکہ کے سردار تھے۔ جب ابرہہ نے کعبہ ان کے حوالے کرنے کا مطالبہ کیا تو عبد المطلب نے سکون سے فرمایا: 'میں اونٹوں کا مالک ہوں، اور کعبہ کا ایک مالک ہے جو خود اس کی حفاظت کرے گا۔'\n\nجب لشکر مکہ کے قریب پہنچا اور حملے کی تیاری شروع کی تو ایک عجیب بات ہوئی۔ بڑا ہاتھی محمود رک گیا۔ خواہ اسے کتنا مارا گیا، چیخا گیا یا دھمکایا گیا، اس نے کعبہ کی طرف ایک قدم بھی اٹھانے سے انکار کر دیا اور زمین پر بیٹھ گیا۔\n\nاچانک آسمان پر سیاہی چھا گئی۔ اللہ نے سمندر کی طرف سے ہزاروں چھوٹے چھوٹے پرندے ابابیل بھیجے۔ ہر پرندہ تین چھوٹی کنکریاں اٹھائے ہوئے تھا — ایک چونچ میں اور دو پنجوں میں۔ وہ لشکر کے اوپر سے گزرے اور پتھر گرانے لگے۔ ہر پتھر جس سپاہی کو لگتا، اسے بالکل تباہ کر دیتا، جیسے قرآن میں ہے 'کھائی ہوئی بھوسے کی طرح'۔\n\nابرہہ خود بیمار ہو کر واپسی پر مر گیا۔ وہ عظیم لشکر مٹ گیا اور کعبہ بالکل محفوظ کھڑا رہا۔ اللہ نے سورۃ الفیل میں یہ قصہ بیان فرمایا تاکہ ہم سب کو یاد رہے: جب اللہ کسی چیز کی حفاظت کا فیصلہ کر لے تو دنیا کی کوئی طاقت — یہاں تک کہ ہاتھیوں کا لشکر بھی — اسے نقصان نہیں پہنچا سکتا۔",
            contentAr = "في العام الذي ولد فيه النبي محمد ﷺ (عام الفيل)، حاول أبرهة الحبشي حاكم اليمن هدم الكعبة المشرفة ليصرف حجاج العرب إلى كنيسة عظيمة بناها في صنعاء.\n\nجهز أبرهة جيشاً جراراً تقدمه فيل عظيم يدعى محمود. خاف أهل مكة واعتصموا بالجبال، بينما وقف عبد المطلب جد النبي ﷺ وقال لأبرهة بثقة: 'أنا رب الإبل، وللبيت رب يحميه'.\n\nوعندما اقترب الجيش من الكعبة وجهزوا الفيل للهجوم، برك الفيل محمود ورفض التقدم نحو البيت الحرام، وكانوا كلما وجهوه لغير الكعبة هرول.\n\nحينها أرسل الله تعالى أسراباً من طير أبابيل تحمل حجارة من سجيل، فرمت بها الجيش فأهلكت كل من أصابته وجعلتهم كعصف مأكول. هلك أبرهة وجيشه وبقيت الكعبة شامخة بحفظ الله ورعايته.",
            contentHi = "जिस साल नबी करीम ﷺ पैदा हुए (हाथियों वाला वर्ष), उसी साल मक्का में एक बहुत बड़ी घटना हुई। यमन के एक शक्तिशाली राजा अबरहा ने एक विशाल और सुंदर चर्च बनाया था और चाहता था कि सभी लोग काबा के बजाय वहाँ आकर प्रार्थना करें। जब अरब फिर भी काबा का सम्मान करते रहे तो अबरहा गुस्से से पागल हो गया।\n\nउसने एक विशाल सेना इकट्ठा की ताकि मक्का पर हमला करके काबा को हमेशा के लिए गिरा दे। अपनी शक्ति दिखाने के लिए वह बड़े-बड़े हाथी भी साथ लाया, जिनमें एक प्रसिद्ध बहुत बड़ा हाथी 'महमूद' भी था। सेना के कदमों से ज़मीन काँपती थी।\n\nमक्का के लोग बहुत घबरा गए। उनकी संख्या कम थी और ऐसी कोई सेना नहीं थी जो हाथियों का मुकाबला कर सके। उन्होंने अपने परिवारों को लेकर पहाड़ों की तरफ रुख किया और दूर से देखने लगे। नबी करीम ﷺ के दादा अब्दुल-मुत्तलिब उस समय मक्का के सरदार थे। जब अबरहा ने काबा उनके हवाले करने की माँग की तो अब्दुल-मुत्तलिब ने शांति से कहा: 'मैं ऊँटों का मालिक हूँ, और काबा का एक मालिक (रब) है जो खुद इसकी रक्षा करेगा।'\n\nजब सेना मक्का के करीब पहुँची और हमले की तैयारी शुरू की तो एक अद्भुत बात हुई। बड़ा हाथी महमूद रुक गया। चाहे उसे कितना भी मारा गया या चिल्लाया गया, उसने काबा की तरफ एक कदम भी उठाने से इनकार कर दिया और ज़मीन पर बैठ गया।\n\nअचानक आसमान पर अँधेरा छा गया। अल्लाह ने समुद्र की तरफ से हज़ारों छोटे-छोटे पक्षी 'अबाबील' भेजे। हर पक्षी तीन छोटे कंकर (पत्थर) उठाए हुए था — एक चोंच में और दो पंजों में। वे सेना के ऊपर से गुज़रे और पत्थर गिराने लगे। हर पत्थर जिस सिपाही को लगता, उसे बिल्कुल नष्ट कर देता, जैसा कुरआन में है 'खाए हुए भूसे की तरह'।\n\nअबरहा खुद बीमार होकर वापसी के रास्ते में मर गया। वह विशाल सेना मिट गई और काबा बिल्कुल सुरक्षित खड़ा रहा। अल्लाह ने सूरह अल-फ़ील में यह कहानी बयान की ताकि हम सबको याद रहे: जब अल्लाह किसी चीज़ की रक्षा का फैसला कर ले तो दुनिया की कोई शक्ति — यहाँ तक कि हाथियों की सेना भी — उसे नुकसान नहीं पहुँचा सकती।"
        ),
    )
}
